// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/ideate/agent_card.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-13 13:14:32 UTC

package ideate

const ()
