// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.4
// source: alis/ideate/ideate.proto

package ideate

import (
	context "context"
	longrunning "google.golang.org/genproto/googleapis/longrunning"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdeateService_AddNote_FullMethodName                   = "/alis.ideate.IdeateService/AddNote"
	IdeateService_AddAudioNote_FullMethodName              = "/alis.ideate.IdeateService/AddAudioNote"
	IdeateService_AddMultiFileUpload_FullMethodName        = "/alis.ideate.IdeateService/AddMultiFileUpload"
	IdeateService_AddAgent_FullMethodName                  = "/alis.ideate.IdeateService/AddAgent"
	IdeateService_InitialiseAgentFeedback_FullMethodName   = "/alis.ideate.IdeateService/InitialiseAgentFeedback"
	IdeateService_GetIdea_FullMethodName                   = "/alis.ideate.IdeateService/GetIdea"
	IdeateService_GetStream_FullMethodName                 = "/alis.ideate.IdeateService/GetStream"
	IdeateService_GetSpec_FullMethodName                   = "/alis.ideate.IdeateService/GetSpec"
	IdeateService_RetrieveIdeaSpecs_FullMethodName         = "/alis.ideate.IdeateService/RetrieveIdeaSpecs"
	IdeateService_GenerateCustomAgentSpec_FullMethodName   = "/alis.ideate.IdeateService/GenerateCustomAgentSpec"
	IdeateService_GenerateAgentFeedbackSpec_FullMethodName = "/alis.ideate.IdeateService/GenerateAgentFeedbackSpec"
	IdeateService_TestIdeateAccess_FullMethodName          = "/alis.ideate.IdeateService/TestIdeateAccess"
	IdeateService_GetOperation_FullMethodName              = "/alis.ideate.IdeateService/GetOperation"
)

// IdeateServiceClient is the client API for IdeateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Public-facing API surface for Alis Ideate
type IdeateServiceClient interface {
	// Adds a new Idea with a note Stream type
	AddNote(ctx context.Context, in *AddNoteRequest, opts ...grpc.CallOption) (*AddNoteResponse, error)
	// Adds a new Idea with a audio note Stream type
	AddAudioNote(ctx context.Context, in *AddAudioNoteRequest, opts ...grpc.CallOption) (*AddAudioNoteResponse, error)
	// Adds a new Idea with a multi-file upload Stream type
	AddMultiFileUpload(ctx context.Context, in *AddMultiFileUploadRequest, opts ...grpc.CallOption) (*AddMultiFileUploadResponse, error)
	// Adds a new Idea with a multi-file upload Stream type
	AddAgent(ctx context.Context, in *AddAgentRequest, opts ...grpc.CallOption) (*AddAgentResponse, error)
	// Provides an easy to use entry point to provide feedback about the interaction with an agent
	//
	// This will essentially create a new Contribution Session within the StreamTarget
	// with two Streams:
	// 1. Agent type Stream - provides context to Ideate about the agent
	// 2. {Whatever the Stream added stream was}
	//
	// The response contains both of the resulting Streams
	InitialiseAgentFeedback(ctx context.Context, in *InitialiseAgentFeedbackRequest, opts ...grpc.CallOption) (*InitialiseAgentFeedbackResponse, error)
	// Gets an Idea by it's name
	GetIdea(ctx context.Context, in *GetIdeaRequest, opts ...grpc.CallOption) (*Idea, error)
	// Gets a Stream by it's name
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*Stream, error)
	// Gets a Spec by it's name
	GetSpec(ctx context.Context, in *GetSpecRequest, opts ...grpc.CallOption) (*Spec, error)
	// Retrieves the set of Specs associated with a specified Idea.
	// If a Spec type is set, only Specs of that type will be returned.
	// Otherwise, all generated Specs for the idea will be returned.
	RetrieveIdeaSpecs(ctx context.Context, in *RetrieveIdeaSpecsRequest, opts ...grpc.CallOption) (*RetrieveIdeaSpecsResponse, error)
	// Generates a Custom Agent spec.
	// This will generate a new spec from an idea, or regenerate an existing spec.
	GenerateCustomAgentSpec(ctx context.Context, in *GenerateCustomAgentSpecRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Generates an Agent Feedback spec.
	// This will generate a new spec from an idea, or regenerate an existing spec.
	GenerateAgentFeedbackSpec(ctx context.Context, in *GenerateAgentFeedbackSpecRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Tests whether the caller has access to Ideate for a specific account
	TestIdeateAccess(ctx context.Context, in *TestIdeateAccessRequest, opts ...grpc.CallOption) (*TestIdeateAccessResponse, error)
	// Returns the given lro
	GetOperation(ctx context.Context, in *longrunning.GetOperationRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
}

type ideateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdeateServiceClient(cc grpc.ClientConnInterface) IdeateServiceClient {
	return &ideateServiceClient{cc}
}

func (c *ideateServiceClient) AddNote(ctx context.Context, in *AddNoteRequest, opts ...grpc.CallOption) (*AddNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNoteResponse)
	err := c.cc.Invoke(ctx, IdeateService_AddNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) AddAudioNote(ctx context.Context, in *AddAudioNoteRequest, opts ...grpc.CallOption) (*AddAudioNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAudioNoteResponse)
	err := c.cc.Invoke(ctx, IdeateService_AddAudioNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) AddMultiFileUpload(ctx context.Context, in *AddMultiFileUploadRequest, opts ...grpc.CallOption) (*AddMultiFileUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMultiFileUploadResponse)
	err := c.cc.Invoke(ctx, IdeateService_AddMultiFileUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) AddAgent(ctx context.Context, in *AddAgentRequest, opts ...grpc.CallOption) (*AddAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAgentResponse)
	err := c.cc.Invoke(ctx, IdeateService_AddAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) InitialiseAgentFeedback(ctx context.Context, in *InitialiseAgentFeedbackRequest, opts ...grpc.CallOption) (*InitialiseAgentFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitialiseAgentFeedbackResponse)
	err := c.cc.Invoke(ctx, IdeateService_InitialiseAgentFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) GetIdea(ctx context.Context, in *GetIdeaRequest, opts ...grpc.CallOption) (*Idea, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Idea)
	err := c.cc.Invoke(ctx, IdeateService_GetIdea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*Stream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stream)
	err := c.cc.Invoke(ctx, IdeateService_GetStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) GetSpec(ctx context.Context, in *GetSpecRequest, opts ...grpc.CallOption) (*Spec, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Spec)
	err := c.cc.Invoke(ctx, IdeateService_GetSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) RetrieveIdeaSpecs(ctx context.Context, in *RetrieveIdeaSpecsRequest, opts ...grpc.CallOption) (*RetrieveIdeaSpecsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveIdeaSpecsResponse)
	err := c.cc.Invoke(ctx, IdeateService_RetrieveIdeaSpecs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) GenerateCustomAgentSpec(ctx context.Context, in *GenerateCustomAgentSpecRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, IdeateService_GenerateCustomAgentSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) GenerateAgentFeedbackSpec(ctx context.Context, in *GenerateAgentFeedbackSpecRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, IdeateService_GenerateAgentFeedbackSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) TestIdeateAccess(ctx context.Context, in *TestIdeateAccessRequest, opts ...grpc.CallOption) (*TestIdeateAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestIdeateAccessResponse)
	err := c.cc.Invoke(ctx, IdeateService_TestIdeateAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ideateServiceClient) GetOperation(ctx context.Context, in *longrunning.GetOperationRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, IdeateService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdeateServiceServer is the server API for IdeateService service.
// All implementations must embed UnimplementedIdeateServiceServer
// for forward compatibility.
//
// Public-facing API surface for Alis Ideate
type IdeateServiceServer interface {
	// Adds a new Idea with a note Stream type
	AddNote(context.Context, *AddNoteRequest) (*AddNoteResponse, error)
	// Adds a new Idea with a audio note Stream type
	AddAudioNote(context.Context, *AddAudioNoteRequest) (*AddAudioNoteResponse, error)
	// Adds a new Idea with a multi-file upload Stream type
	AddMultiFileUpload(context.Context, *AddMultiFileUploadRequest) (*AddMultiFileUploadResponse, error)
	// Adds a new Idea with a multi-file upload Stream type
	AddAgent(context.Context, *AddAgentRequest) (*AddAgentResponse, error)
	// Provides an easy to use entry point to provide feedback about the interaction with an agent
	//
	// This will essentially create a new Contribution Session within the StreamTarget
	// with two Streams:
	// 1. Agent type Stream - provides context to Ideate about the agent
	// 2. {Whatever the Stream added stream was}
	//
	// The response contains both of the resulting Streams
	InitialiseAgentFeedback(context.Context, *InitialiseAgentFeedbackRequest) (*InitialiseAgentFeedbackResponse, error)
	// Gets an Idea by it's name
	GetIdea(context.Context, *GetIdeaRequest) (*Idea, error)
	// Gets a Stream by it's name
	GetStream(context.Context, *GetStreamRequest) (*Stream, error)
	// Gets a Spec by it's name
	GetSpec(context.Context, *GetSpecRequest) (*Spec, error)
	// Retrieves the set of Specs associated with a specified Idea.
	// If a Spec type is set, only Specs of that type will be returned.
	// Otherwise, all generated Specs for the idea will be returned.
	RetrieveIdeaSpecs(context.Context, *RetrieveIdeaSpecsRequest) (*RetrieveIdeaSpecsResponse, error)
	// Generates a Custom Agent spec.
	// This will generate a new spec from an idea, or regenerate an existing spec.
	GenerateCustomAgentSpec(context.Context, *GenerateCustomAgentSpecRequest) (*longrunning.Operation, error)
	// Generates an Agent Feedback spec.
	// This will generate a new spec from an idea, or regenerate an existing spec.
	GenerateAgentFeedbackSpec(context.Context, *GenerateAgentFeedbackSpecRequest) (*longrunning.Operation, error)
	// Tests whether the caller has access to Ideate for a specific account
	TestIdeateAccess(context.Context, *TestIdeateAccessRequest) (*TestIdeateAccessResponse, error)
	// Returns the given lro
	GetOperation(context.Context, *longrunning.GetOperationRequest) (*longrunning.Operation, error)
	mustEmbedUnimplementedIdeateServiceServer()
}

// UnimplementedIdeateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdeateServiceServer struct{}

func (UnimplementedIdeateServiceServer) AddNote(context.Context, *AddNoteRequest) (*AddNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNote not implemented")
}
func (UnimplementedIdeateServiceServer) AddAudioNote(context.Context, *AddAudioNoteRequest) (*AddAudioNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAudioNote not implemented")
}
func (UnimplementedIdeateServiceServer) AddMultiFileUpload(context.Context, *AddMultiFileUploadRequest) (*AddMultiFileUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMultiFileUpload not implemented")
}
func (UnimplementedIdeateServiceServer) AddAgent(context.Context, *AddAgentRequest) (*AddAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAgent not implemented")
}
func (UnimplementedIdeateServiceServer) InitialiseAgentFeedback(context.Context, *InitialiseAgentFeedbackRequest) (*InitialiseAgentFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitialiseAgentFeedback not implemented")
}
func (UnimplementedIdeateServiceServer) GetIdea(context.Context, *GetIdeaRequest) (*Idea, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdea not implemented")
}
func (UnimplementedIdeateServiceServer) GetStream(context.Context, *GetStreamRequest) (*Stream, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedIdeateServiceServer) GetSpec(context.Context, *GetSpecRequest) (*Spec, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpec not implemented")
}
func (UnimplementedIdeateServiceServer) RetrieveIdeaSpecs(context.Context, *RetrieveIdeaSpecsRequest) (*RetrieveIdeaSpecsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveIdeaSpecs not implemented")
}
func (UnimplementedIdeateServiceServer) GenerateCustomAgentSpec(context.Context, *GenerateCustomAgentSpecRequest) (*longrunning.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCustomAgentSpec not implemented")
}
func (UnimplementedIdeateServiceServer) GenerateAgentFeedbackSpec(context.Context, *GenerateAgentFeedbackSpecRequest) (*longrunning.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateAgentFeedbackSpec not implemented")
}
func (UnimplementedIdeateServiceServer) TestIdeateAccess(context.Context, *TestIdeateAccessRequest) (*TestIdeateAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestIdeateAccess not implemented")
}
func (UnimplementedIdeateServiceServer) GetOperation(context.Context, *longrunning.GetOperationRequest) (*longrunning.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedIdeateServiceServer) mustEmbedUnimplementedIdeateServiceServer() {}
func (UnimplementedIdeateServiceServer) testEmbeddedByValue()                       {}

// UnsafeIdeateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdeateServiceServer will
// result in compilation errors.
type UnsafeIdeateServiceServer interface {
	mustEmbedUnimplementedIdeateServiceServer()
}

func RegisterIdeateServiceServer(s grpc.ServiceRegistrar, srv IdeateServiceServer) {
	// If the following call panics, it indicates UnimplementedIdeateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdeateService_ServiceDesc, srv)
}

func _IdeateService_AddNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).AddNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_AddNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).AddNote(ctx, req.(*AddNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_AddAudioNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAudioNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).AddAudioNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_AddAudioNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).AddAudioNote(ctx, req.(*AddAudioNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_AddMultiFileUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMultiFileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).AddMultiFileUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_AddMultiFileUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).AddMultiFileUpload(ctx, req.(*AddMultiFileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_AddAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).AddAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_AddAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).AddAgent(ctx, req.(*AddAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_InitialiseAgentFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitialiseAgentFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).InitialiseAgentFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_InitialiseAgentFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).InitialiseAgentFeedback(ctx, req.(*InitialiseAgentFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_GetIdea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdeaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).GetIdea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_GetIdea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).GetIdea(ctx, req.(*GetIdeaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_GetStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_GetSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).GetSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_GetSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).GetSpec(ctx, req.(*GetSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_RetrieveIdeaSpecs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveIdeaSpecsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).RetrieveIdeaSpecs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_RetrieveIdeaSpecs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).RetrieveIdeaSpecs(ctx, req.(*RetrieveIdeaSpecsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_GenerateCustomAgentSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCustomAgentSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).GenerateCustomAgentSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_GenerateCustomAgentSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).GenerateCustomAgentSpec(ctx, req.(*GenerateCustomAgentSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_GenerateAgentFeedbackSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAgentFeedbackSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).GenerateAgentFeedbackSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_GenerateAgentFeedbackSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).GenerateAgentFeedbackSpec(ctx, req.(*GenerateAgentFeedbackSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_TestIdeateAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestIdeateAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).TestIdeateAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_TestIdeateAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).TestIdeateAccess(ctx, req.(*TestIdeateAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdeateService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(longrunning.GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeateServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdeateService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeateServiceServer).GetOperation(ctx, req.(*longrunning.GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdeateService_ServiceDesc is the grpc.ServiceDesc for IdeateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdeateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alis.ideate.IdeateService",
	HandlerType: (*IdeateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNote",
			Handler:    _IdeateService_AddNote_Handler,
		},
		{
			MethodName: "AddAudioNote",
			Handler:    _IdeateService_AddAudioNote_Handler,
		},
		{
			MethodName: "AddMultiFileUpload",
			Handler:    _IdeateService_AddMultiFileUpload_Handler,
		},
		{
			MethodName: "AddAgent",
			Handler:    _IdeateService_AddAgent_Handler,
		},
		{
			MethodName: "InitialiseAgentFeedback",
			Handler:    _IdeateService_InitialiseAgentFeedback_Handler,
		},
		{
			MethodName: "GetIdea",
			Handler:    _IdeateService_GetIdea_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _IdeateService_GetStream_Handler,
		},
		{
			MethodName: "GetSpec",
			Handler:    _IdeateService_GetSpec_Handler,
		},
		{
			MethodName: "RetrieveIdeaSpecs",
			Handler:    _IdeateService_RetrieveIdeaSpecs_Handler,
		},
		{
			MethodName: "GenerateCustomAgentSpec",
			Handler:    _IdeateService_GenerateCustomAgentSpec_Handler,
		},
		{
			MethodName: "GenerateAgentFeedbackSpec",
			Handler:    _IdeateService_GenerateAgentFeedbackSpec_Handler,
		},
		{
			MethodName: "TestIdeateAccess",
			Handler:    _IdeateService_TestIdeateAccess_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _IdeateService_GetOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alis/ideate/ideate.proto",
}
