// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/ideate/idea.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-05-04 14:07:14 UTC

package ideate

const ()
