// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/ideate/idea.proto

package ideate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The state of the Idea
type Idea_State int32

const (
	// Unspecified
	Idea_STATE_UNSPECIFIED Idea_State = 0
	// The Idea is considered NEW when initially added
	// and not yet processed. It will move into PROCESSING
	// when augmentation starts taking place and the ACTIVE
	// once augmented.
	Idea_NEW Idea_State = 1
	// The Idea is being augmented based on the streams
	Idea_PROCESSING Idea_State = 2
	// The Idea is active and being worked on
	Idea_ACTIVE Idea_State = 3
	// The Idea has been archived and is no longer relevant
	Idea_ARCHIVED Idea_State = 4
	// The Idea has not received any attention within a prolonged
	// period and therefore is regarded as stale. An Idea can become
	// active again if any new contributions are made to it.
	Idea_STALE Idea_State = 5
)

// Enum value maps for Idea_State.
var (
	Idea_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "NEW",
		2: "PROCESSING",
		3: "ACTIVE",
		4: "ARCHIVED",
		5: "STALE",
	}
	Idea_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"NEW":               1,
		"PROCESSING":        2,
		"ACTIVE":            3,
		"ARCHIVED":          4,
		"STALE":             5,
	}
)

func (x Idea_State) Enum() *Idea_State {
	p := new(Idea_State)
	*p = x
	return p
}

func (x Idea_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Idea_State) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_ideate_idea_proto_enumTypes[0].Descriptor()
}

func (Idea_State) Type() protoreflect.EnumType {
	return &file_alis_ideate_idea_proto_enumTypes[0]
}

func (x Idea_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Idea_State.Descriptor instead.
func (Idea_State) EnumDescriptor() ([]byte, []int) {
	return file_alis_ideate_idea_proto_rawDescGZIP(), []int{0, 0}
}

// Representation of an idea.
//
// At it's most simplest version, this represents any thought
// that one wants to capture, irrespective of how developed
// and fleshed out the Idea is. Ideas can grow as Streams are added
// to it.
//
// Metaphorically, an Idea is a river - a complete, dynamic system that
// captures the cumulative flow of thought, knowledge, and collaborative
// exploration. While individual Streams contribute to it, the Idea represents
// the confluence of the multiple Streams.
//
// Ideas can be formalized, reviewed and decisions can be
// made by various stakeholders in order to upgrade an
// Idea into an implementation of a product/service
// on the Alis Build platform. This can be done on a
// spectrum of self-service to turnkey solutions.
type Idea struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique name of the Idea.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The display title of the Idea.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The state of the Idea
	State Idea_State `protobuf:"varint,3,opt,name=state,proto3,enum=alis.ideate.Idea_State" json:"state,omitempty"`
	// The set of ManagedSpecs that Ideate is responsible for
	// keeping up to date as new Streams are added to the Idea.
	ManagedSpecs *Idea_ManagedSpecs `protobuf:"bytes,4,opt,name=managed_specs,json=managedSpecs,proto3" json:"managed_specs,omitempty"`
	// The account this Idea belongs to.
	Account string `protobuf:"bytes,96,opt,name=account,proto3" json:"account,omitempty"`
	// The creation time of the Idea.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,97,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last time the Idea was updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Idea) Reset() {
	*x = Idea{}
	mi := &file_alis_ideate_idea_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idea) ProtoMessage() {}

func (x *Idea) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_idea_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idea.ProtoReflect.Descriptor instead.
func (*Idea) Descriptor() ([]byte, []int) {
	return file_alis_ideate_idea_proto_rawDescGZIP(), []int{0}
}

func (x *Idea) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Idea) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Idea) GetState() Idea_State {
	if x != nil {
		return x.State
	}
	return Idea_STATE_UNSPECIFIED
}

func (x *Idea) GetManagedSpecs() *Idea_ManagedSpecs {
	if x != nil {
		return x.ManagedSpecs
	}
	return nil
}

func (x *Idea) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Idea) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Idea) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Request message for GetIdea
type GetIdeaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the Idea to get
	// Format: ideas/*
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The fields to return in snake_case.
	// All fields are returned if not set.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdeaRequest) Reset() {
	*x = GetIdeaRequest{}
	mi := &file_alis_ideate_idea_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdeaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdeaRequest) ProtoMessage() {}

func (x *GetIdeaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_idea_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdeaRequest.ProtoReflect.Descriptor instead.
func (*GetIdeaRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_idea_proto_rawDescGZIP(), []int{1}
}

func (x *GetIdeaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetIdeaRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// The set of ManagedSpecs that Ideate is responsible for
// keeping up to date as new Streams are added to the Idea.
type Idea_ManagedSpecs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Idea brief
	// Format: specs/*
	IdeaBrief string `protobuf:"bytes,1,opt,name=idea_brief,json=ideaBrief,proto3" json:"idea_brief,omitempty"`
	// The current process spec
	// Format: specs/*
	CurrentProcess string `protobuf:"bytes,2,opt,name=current_process,json=currentProcess,proto3" json:"current_process,omitempty"`
	// The stakeholder map
	// Format: specs/*
	StakeholderMap string `protobuf:"bytes,3,opt,name=stakeholder_map,json=stakeholderMap,proto3" json:"stakeholder_map,omitempty"`
	// The pain points
	// Format: specs/*
	PainPoints string `protobuf:"bytes,4,opt,name=pain_points,json=painPoints,proto3" json:"pain_points,omitempty"`
	// The jargon
	// Format: specs/*
	Jargon string `protobuf:"bytes,5,opt,name=jargon,proto3" json:"jargon,omitempty"`
	// The technology landscape
	// Format: specs/*
	TechnologyLandscape string `protobuf:"bytes,6,opt,name=technology_landscape,json=technologyLandscape,proto3" json:"technology_landscape,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Idea_ManagedSpecs) Reset() {
	*x = Idea_ManagedSpecs{}
	mi := &file_alis_ideate_idea_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idea_ManagedSpecs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idea_ManagedSpecs) ProtoMessage() {}

func (x *Idea_ManagedSpecs) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_idea_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idea_ManagedSpecs.ProtoReflect.Descriptor instead.
func (*Idea_ManagedSpecs) Descriptor() ([]byte, []int) {
	return file_alis_ideate_idea_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Idea_ManagedSpecs) GetIdeaBrief() string {
	if x != nil {
		return x.IdeaBrief
	}
	return ""
}

func (x *Idea_ManagedSpecs) GetCurrentProcess() string {
	if x != nil {
		return x.CurrentProcess
	}
	return ""
}

func (x *Idea_ManagedSpecs) GetStakeholderMap() string {
	if x != nil {
		return x.StakeholderMap
	}
	return ""
}

func (x *Idea_ManagedSpecs) GetPainPoints() string {
	if x != nil {
		return x.PainPoints
	}
	return ""
}

func (x *Idea_ManagedSpecs) GetJargon() string {
	if x != nil {
		return x.Jargon
	}
	return ""
}

func (x *Idea_ManagedSpecs) GetTechnologyLandscape() string {
	if x != nil {
		return x.TechnologyLandscape
	}
	return ""
}

var File_alis_ideate_idea_proto protoreflect.FileDescriptor

const file_alis_ideate_idea_proto_rawDesc = "" +
	"\n" +
	"\x16alis/ideate/idea.proto\x12\valis.ideate\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x05\n" +
	"\x04Idea\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12-\n" +
	"\x05state\x18\x03 \x01(\x0e2\x17.alis.ideate.Idea.StateR\x05state\x12C\n" +
	"\rmanaged_specs\x18\x04 \x01(\v2\x1e.alis.ideate.Idea.ManagedSpecsR\fmanagedSpecs\x12\x18\n" +
	"\aaccount\x18` \x01(\tR\aaccount\x12;\n" +
	"\vcreate_time\x18a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x1a\xeb\x01\n" +
	"\fManagedSpecs\x12\x1d\n" +
	"\n" +
	"idea_brief\x18\x01 \x01(\tR\tideaBrief\x12'\n" +
	"\x0fcurrent_process\x18\x02 \x01(\tR\x0ecurrentProcess\x12'\n" +
	"\x0fstakeholder_map\x18\x03 \x01(\tR\x0estakeholderMap\x12\x1f\n" +
	"\vpain_points\x18\x04 \x01(\tR\n" +
	"painPoints\x12\x16\n" +
	"\x06jargon\x18\x05 \x01(\tR\x06jargon\x121\n" +
	"\x14technology_landscape\x18\x06 \x01(\tR\x13technologyLandscape\"\\\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x03\x12\f\n" +
	"\bARCHIVED\x10\x04\x12\t\n" +
	"\x05STALE\x10\x05\"]\n" +
	"\x0eGetIdeaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMaskB0Z.github.com/alis-exchange/ideate-go/alis/ideateb\x06proto3"

var (
	file_alis_ideate_idea_proto_rawDescOnce sync.Once
	file_alis_ideate_idea_proto_rawDescData []byte
)

func file_alis_ideate_idea_proto_rawDescGZIP() []byte {
	file_alis_ideate_idea_proto_rawDescOnce.Do(func() {
		file_alis_ideate_idea_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_ideate_idea_proto_rawDesc), len(file_alis_ideate_idea_proto_rawDesc)))
	})
	return file_alis_ideate_idea_proto_rawDescData
}

var file_alis_ideate_idea_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alis_ideate_idea_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_alis_ideate_idea_proto_goTypes = []any{
	(Idea_State)(0),               // 0: alis.ideate.Idea.State
	(*Idea)(nil),                  // 1: alis.ideate.Idea
	(*GetIdeaRequest)(nil),        // 2: alis.ideate.GetIdeaRequest
	(*Idea_ManagedSpecs)(nil),     // 3: alis.ideate.Idea.ManagedSpecs
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 5: google.protobuf.FieldMask
}
var file_alis_ideate_idea_proto_depIdxs = []int32{
	0, // 0: alis.ideate.Idea.state:type_name -> alis.ideate.Idea.State
	3, // 1: alis.ideate.Idea.managed_specs:type_name -> alis.ideate.Idea.ManagedSpecs
	4, // 2: alis.ideate.Idea.create_time:type_name -> google.protobuf.Timestamp
	4, // 3: alis.ideate.Idea.update_time:type_name -> google.protobuf.Timestamp
	5, // 4: alis.ideate.GetIdeaRequest.read_mask:type_name -> google.protobuf.FieldMask
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_alis_ideate_idea_proto_init() }
func file_alis_ideate_idea_proto_init() {
	if File_alis_ideate_idea_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_ideate_idea_proto_rawDesc), len(file_alis_ideate_idea_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_ideate_idea_proto_goTypes,
		DependencyIndexes: file_alis_ideate_idea_proto_depIdxs,
		EnumInfos:         file_alis_ideate_idea_proto_enumTypes,
		MessageInfos:      file_alis_ideate_idea_proto_msgTypes,
	}.Build()
	File_alis_ideate_idea_proto = out.File
	file_alis_ideate_idea_proto_goTypes = nil
	file_alis_ideate_idea_proto_depIdxs = nil
}
