// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/ideate/ideate.proto

package ideate

import (
	longrunning "google.golang.org/genproto/googleapis/longrunning"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestIdeateAccessResponse_Restriction int32

const (
	// Unspecified state, should be interpreted as not having any restrictions
	TestIdeateAccessResponse_RESTRICTION_UNSPECIFIED TestIdeateAccessResponse_Restriction = 0
	// The account has a restriction due to not having a seat
	TestIdeateAccessResponse_NO_SEAT TestIdeateAccessResponse_Restriction = 1
	// The account has a restriction due to trial expiry
	TestIdeateAccessResponse_TRIAL_EXPIRED TestIdeateAccessResponse_Restriction = 2
	// The account has a restriction due to plan limits reached
	TestIdeateAccessResponse_PLAN_LIMITS_REACHED TestIdeateAccessResponse_Restriction = 3
)

// Enum value maps for TestIdeateAccessResponse_Restriction.
var (
	TestIdeateAccessResponse_Restriction_name = map[int32]string{
		0: "RESTRICTION_UNSPECIFIED",
		1: "NO_SEAT",
		2: "TRIAL_EXPIRED",
		3: "PLAN_LIMITS_REACHED",
	}
	TestIdeateAccessResponse_Restriction_value = map[string]int32{
		"RESTRICTION_UNSPECIFIED": 0,
		"NO_SEAT":                 1,
		"TRIAL_EXPIRED":           2,
		"PLAN_LIMITS_REACHED":     3,
	}
)

func (x TestIdeateAccessResponse_Restriction) Enum() *TestIdeateAccessResponse_Restriction {
	p := new(TestIdeateAccessResponse_Restriction)
	*p = x
	return p
}

func (x TestIdeateAccessResponse_Restriction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestIdeateAccessResponse_Restriction) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_ideate_ideate_proto_enumTypes[0].Descriptor()
}

func (TestIdeateAccessResponse_Restriction) Type() protoreflect.EnumType {
	return &file_alis_ideate_ideate_proto_enumTypes[0]
}

func (x TestIdeateAccessResponse_Restriction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestIdeateAccessResponse_Restriction.Descriptor instead.
func (TestIdeateAccessResponse_Restriction) EnumDescriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{11, 0}
}

// Request message for AddNote
type AddNoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream target sets the expected behaviour of the Stream to create.
	// The resulting Stream will be created within either a new or existing idea,
	// or can be in the fulfilment of a context request.
	//
	// Types that are valid to be assigned to StreamTarget:
	//
	//	*AddNoteRequest_Account
	//	*AddNoteRequest_Idea
	//	*AddNoteRequest_Token
	//	*AddNoteRequest_ContributionSession
	StreamTarget isAddNoteRequest_StreamTarget `protobuf_oneof:"stream_target"`
	// The content of the note
	Content       string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNoteRequest) Reset() {
	*x = AddNoteRequest{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNoteRequest) ProtoMessage() {}

func (x *AddNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNoteRequest.ProtoReflect.Descriptor instead.
func (*AddNoteRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{0}
}

func (x *AddNoteRequest) GetStreamTarget() isAddNoteRequest_StreamTarget {
	if x != nil {
		return x.StreamTarget
	}
	return nil
}

func (x *AddNoteRequest) GetAccount() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddNoteRequest_Account); ok {
			return x.Account
		}
	}
	return ""
}

func (x *AddNoteRequest) GetIdea() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddNoteRequest_Idea); ok {
			return x.Idea
		}
	}
	return ""
}

func (x *AddNoteRequest) GetToken() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddNoteRequest_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *AddNoteRequest) GetContributionSession() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddNoteRequest_ContributionSession); ok {
			return x.ContributionSession
		}
	}
	return ""
}

func (x *AddNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type isAddNoteRequest_StreamTarget interface {
	isAddNoteRequest_StreamTarget()
}

type AddNoteRequest_Account struct {
	// The Account that the Idea will be associated with.
	// Format: accounts/*
	//
	// Target: Create a new Idea, ie. do not add Stream to an existing Idea
	Account string `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type AddNoteRequest_Idea struct {
	// The Idea to add the Stream to. Will create if not specified.
	// Format: ideas/*
	//
	// Target: Add Stream to an existing Idea.
	Idea string `protobuf:"bytes,2,opt,name=idea,proto3,oneof"`
}

type AddNoteRequest_Token struct {
	// The token as part of the URL provided by the
	// GenerateProposalExecutionSignedUrl method.
	//
	// Format: `{payload}.{signature}`
	Token string `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

type AddNoteRequest_ContributionSession struct {
	// A Contribution Session to link the Stream to
	// Format: ideas/*/contributionSessions/*
	ContributionSession string `protobuf:"bytes,4,opt,name=contribution_session,json=contributionSession,proto3,oneof"`
}

func (*AddNoteRequest_Account) isAddNoteRequest_StreamTarget() {}

func (*AddNoteRequest_Idea) isAddNoteRequest_StreamTarget() {}

func (*AddNoteRequest_Token) isAddNoteRequest_StreamTarget() {}

func (*AddNoteRequest_ContributionSession) isAddNoteRequest_StreamTarget() {}

// Response message for AddNote
type AddNoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream that was created
	Stream        *Stream `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNoteResponse) Reset() {
	*x = AddNoteResponse{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNoteResponse) ProtoMessage() {}

func (x *AddNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNoteResponse.ProtoReflect.Descriptor instead.
func (*AddNoteResponse) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{1}
}

func (x *AddNoteResponse) GetStream() *Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

// Request message for AddAudioNote
type AddAudioNoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream target sets the expected behaviour of the Stream to create.
	// The resulting Stream will be created within either a new or existing idea,
	// or can be in the fulfilment of a context request.
	//
	// Types that are valid to be assigned to StreamTarget:
	//
	//	*AddAudioNoteRequest_Account
	//	*AddAudioNoteRequest_Idea
	//	*AddAudioNoteRequest_Token
	//	*AddAudioNoteRequest_ContributionSession
	StreamTarget isAddAudioNoteRequest_StreamTarget `protobuf_oneof:"stream_target"`
	// The MIME type of the audio note
	// supports all 'audio/*' types
	MimeType string `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Origin for cors purposes
	// This is from where the resumable uploads will be made
	// For example: https://myconsole.myweb.com
	OriginUri     string `protobuf:"bytes,6,opt,name=origin_uri,json=originUri,proto3" json:"origin_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAudioNoteRequest) Reset() {
	*x = AddAudioNoteRequest{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAudioNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAudioNoteRequest) ProtoMessage() {}

func (x *AddAudioNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAudioNoteRequest.ProtoReflect.Descriptor instead.
func (*AddAudioNoteRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{2}
}

func (x *AddAudioNoteRequest) GetStreamTarget() isAddAudioNoteRequest_StreamTarget {
	if x != nil {
		return x.StreamTarget
	}
	return nil
}

func (x *AddAudioNoteRequest) GetAccount() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddAudioNoteRequest_Account); ok {
			return x.Account
		}
	}
	return ""
}

func (x *AddAudioNoteRequest) GetIdea() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddAudioNoteRequest_Idea); ok {
			return x.Idea
		}
	}
	return ""
}

func (x *AddAudioNoteRequest) GetToken() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddAudioNoteRequest_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *AddAudioNoteRequest) GetContributionSession() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddAudioNoteRequest_ContributionSession); ok {
			return x.ContributionSession
		}
	}
	return ""
}

func (x *AddAudioNoteRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AddAudioNoteRequest) GetOriginUri() string {
	if x != nil {
		return x.OriginUri
	}
	return ""
}

type isAddAudioNoteRequest_StreamTarget interface {
	isAddAudioNoteRequest_StreamTarget()
}

type AddAudioNoteRequest_Account struct {
	// The Account that the Idea will be associated with.
	// Format: accounts/*
	//
	// Target: Create a new Idea, ie. do not add Stream to an existing Idea
	Account string `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type AddAudioNoteRequest_Idea struct {
	// The Idea to add the Stream to. Will create if not specified.
	// Format: ideas/*
	//
	// Target: Add Stream to an existing Idea.
	Idea string `protobuf:"bytes,2,opt,name=idea,proto3,oneof"`
}

type AddAudioNoteRequest_Token struct {
	// The token as part of the URL provided by the
	// GenerateProposalExecutionSignedUrl method.
	//
	// Format: `{payload}.{signature}`
	Token string `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

type AddAudioNoteRequest_ContributionSession struct {
	// A Contribution Session to link the Stream to
	// Format: ideas/*/contributionSessions/*
	ContributionSession string `protobuf:"bytes,4,opt,name=contribution_session,json=contributionSession,proto3,oneof"`
}

func (*AddAudioNoteRequest_Account) isAddAudioNoteRequest_StreamTarget() {}

func (*AddAudioNoteRequest_Idea) isAddAudioNoteRequest_StreamTarget() {}

func (*AddAudioNoteRequest_Token) isAddAudioNoteRequest_StreamTarget() {}

func (*AddAudioNoteRequest_ContributionSession) isAddAudioNoteRequest_StreamTarget() {}

// Response message for AddAudioNote
type AddAudioNoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream that was created
	Stream *Stream `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// The link that can be used to upload the audio note to.
	UploadUri     string `protobuf:"bytes,2,opt,name=upload_uri,json=uploadUri,proto3" json:"upload_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAudioNoteResponse) Reset() {
	*x = AddAudioNoteResponse{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAudioNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAudioNoteResponse) ProtoMessage() {}

func (x *AddAudioNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAudioNoteResponse.ProtoReflect.Descriptor instead.
func (*AddAudioNoteResponse) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{3}
}

func (x *AddAudioNoteResponse) GetStream() *Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *AddAudioNoteResponse) GetUploadUri() string {
	if x != nil {
		return x.UploadUri
	}
	return ""
}

// Request message for AddMultiFileUpload
type AddMultiFileUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream target sets the expected behaviour of the Stream to create.
	// The resulting Stream will be created within either a new or existing idea,
	// or can be in the fulfilment of a context request.
	//
	// Types that are valid to be assigned to StreamTarget:
	//
	//	*AddMultiFileUploadRequest_Account
	//	*AddMultiFileUploadRequest_Idea
	//	*AddMultiFileUploadRequest_Token
	//	*AddMultiFileUploadRequest_ContributionSession
	StreamTarget isAddMultiFileUploadRequest_StreamTarget `protobuf_oneof:"stream_target"`
	// A note added for context, in valid markdown
	Note string `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	// The set of files to upload
	Files []*AddMultiFileUploadRequest_File `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
	// Origin for cors purposes
	// This is from where the resumable uploads will be made
	// For example: https://myconsole.myweb.com
	OriginUri     string `protobuf:"bytes,7,opt,name=origin_uri,json=originUri,proto3" json:"origin_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMultiFileUploadRequest) Reset() {
	*x = AddMultiFileUploadRequest{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMultiFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMultiFileUploadRequest) ProtoMessage() {}

func (x *AddMultiFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMultiFileUploadRequest.ProtoReflect.Descriptor instead.
func (*AddMultiFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{4}
}

func (x *AddMultiFileUploadRequest) GetStreamTarget() isAddMultiFileUploadRequest_StreamTarget {
	if x != nil {
		return x.StreamTarget
	}
	return nil
}

func (x *AddMultiFileUploadRequest) GetAccount() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddMultiFileUploadRequest_Account); ok {
			return x.Account
		}
	}
	return ""
}

func (x *AddMultiFileUploadRequest) GetIdea() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddMultiFileUploadRequest_Idea); ok {
			return x.Idea
		}
	}
	return ""
}

func (x *AddMultiFileUploadRequest) GetToken() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddMultiFileUploadRequest_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *AddMultiFileUploadRequest) GetContributionSession() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddMultiFileUploadRequest_ContributionSession); ok {
			return x.ContributionSession
		}
	}
	return ""
}

func (x *AddMultiFileUploadRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *AddMultiFileUploadRequest) GetFiles() []*AddMultiFileUploadRequest_File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AddMultiFileUploadRequest) GetOriginUri() string {
	if x != nil {
		return x.OriginUri
	}
	return ""
}

type isAddMultiFileUploadRequest_StreamTarget interface {
	isAddMultiFileUploadRequest_StreamTarget()
}

type AddMultiFileUploadRequest_Account struct {
	// The Account that the Idea will be associated with.
	// Format: accounts/*
	//
	// Target: Create a new Idea, ie. do not add Stream to an existing Idea
	Account string `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type AddMultiFileUploadRequest_Idea struct {
	// The Idea to add the Stream to. Will create if not specified.
	// Format: ideas/*
	//
	// Target: Add Stream to an existing Idea.
	Idea string `protobuf:"bytes,2,opt,name=idea,proto3,oneof"`
}

type AddMultiFileUploadRequest_Token struct {
	// The token as part of the URL provided by the
	// GenerateProposalExecutionSignedUrl method.
	//
	// Format: `{payload}.{signature}`
	Token string `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

type AddMultiFileUploadRequest_ContributionSession struct {
	// A Contribution Session to link the Stream to
	// Format: ideas/*/contributionSessions/*
	ContributionSession string `protobuf:"bytes,4,opt,name=contribution_session,json=contributionSession,proto3,oneof"`
}

func (*AddMultiFileUploadRequest_Account) isAddMultiFileUploadRequest_StreamTarget() {}

func (*AddMultiFileUploadRequest_Idea) isAddMultiFileUploadRequest_StreamTarget() {}

func (*AddMultiFileUploadRequest_Token) isAddMultiFileUploadRequest_StreamTarget() {}

func (*AddMultiFileUploadRequest_ContributionSession) isAddMultiFileUploadRequest_StreamTarget() {}

// Response message for AddMultiFileUpload method
type AddMultiFileUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream that was created
	Stream *Stream `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// The set of files and their upload urls
	Files         []*AddMultiFileUploadResponse_File `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMultiFileUploadResponse) Reset() {
	*x = AddMultiFileUploadResponse{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMultiFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMultiFileUploadResponse) ProtoMessage() {}

func (x *AddMultiFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMultiFileUploadResponse.ProtoReflect.Descriptor instead.
func (*AddMultiFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{5}
}

func (x *AddMultiFileUploadResponse) GetStream() *Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *AddMultiFileUploadResponse) GetFiles() []*AddMultiFileUploadResponse_File {
	if x != nil {
		return x.Files
	}
	return nil
}

// Request message for AddAgent
type AddAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream target sets the expected behaviour of the Stream to create.
	// The resulting Stream will be created within either a new or existing idea,
	// or can be in the fulfilment of a context request.
	//
	// Types that are valid to be assigned to StreamTarget:
	//
	//	*AddAgentRequest_Account
	//	*AddAgentRequest_Idea
	//	*AddAgentRequest_Token
	//	*AddAgentRequest_ContributionSession
	StreamTarget isAddAgentRequest_StreamTarget `protobuf_oneof:"stream_target"`
	// The Agent Stream requires an Agent Card to be
	// added to it. This can be done in one of two ways:
	// 1. By providing an Agent Card directly
	// 2. By providing a URI to an Agent Card
	//
	// Types that are valid to be assigned to AgentCardSource:
	//
	//	*AddAgentRequest_AgentCard
	//	*AddAgentRequest_AgentCardUri
	AgentCardSource isAddAgentRequest_AgentCardSource `protobuf_oneof:"agent_card_source"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddAgentRequest) Reset() {
	*x = AddAgentRequest{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgentRequest) ProtoMessage() {}

func (x *AddAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgentRequest.ProtoReflect.Descriptor instead.
func (*AddAgentRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{6}
}

func (x *AddAgentRequest) GetStreamTarget() isAddAgentRequest_StreamTarget {
	if x != nil {
		return x.StreamTarget
	}
	return nil
}

func (x *AddAgentRequest) GetAccount() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddAgentRequest_Account); ok {
			return x.Account
		}
	}
	return ""
}

func (x *AddAgentRequest) GetIdea() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddAgentRequest_Idea); ok {
			return x.Idea
		}
	}
	return ""
}

func (x *AddAgentRequest) GetToken() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddAgentRequest_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *AddAgentRequest) GetContributionSession() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*AddAgentRequest_ContributionSession); ok {
			return x.ContributionSession
		}
	}
	return ""
}

func (x *AddAgentRequest) GetAgentCardSource() isAddAgentRequest_AgentCardSource {
	if x != nil {
		return x.AgentCardSource
	}
	return nil
}

func (x *AddAgentRequest) GetAgentCard() *AgentCard {
	if x != nil {
		if x, ok := x.AgentCardSource.(*AddAgentRequest_AgentCard); ok {
			return x.AgentCard
		}
	}
	return nil
}

func (x *AddAgentRequest) GetAgentCardUri() string {
	if x != nil {
		if x, ok := x.AgentCardSource.(*AddAgentRequest_AgentCardUri); ok {
			return x.AgentCardUri
		}
	}
	return ""
}

type isAddAgentRequest_StreamTarget interface {
	isAddAgentRequest_StreamTarget()
}

type AddAgentRequest_Account struct {
	// The Account that the Idea will be associated with.
	// Format: accounts/*
	//
	// Target: Create a new Idea, ie. do not add Stream to an existing Idea
	Account string `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type AddAgentRequest_Idea struct {
	// The Idea to add the Stream to. Will create if not specified.
	// Format: ideas/*
	//
	// Target: Add Stream to an existing Idea.
	Idea string `protobuf:"bytes,2,opt,name=idea,proto3,oneof"`
}

type AddAgentRequest_Token struct {
	// The token as part of the URL provided by the
	// GenerateProposalExecutionSignedUrl method.
	//
	// Format: `{payload}.{signature}`
	Token string `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

type AddAgentRequest_ContributionSession struct {
	// A Contribution Session to link the Stream to
	// Format: ideas/*/contributionSessions/*
	ContributionSession string `protobuf:"bytes,4,opt,name=contribution_session,json=contributionSession,proto3,oneof"`
}

func (*AddAgentRequest_Account) isAddAgentRequest_StreamTarget() {}

func (*AddAgentRequest_Idea) isAddAgentRequest_StreamTarget() {}

func (*AddAgentRequest_Token) isAddAgentRequest_StreamTarget() {}

func (*AddAgentRequest_ContributionSession) isAddAgentRequest_StreamTarget() {}

type isAddAgentRequest_AgentCardSource interface {
	isAddAgentRequest_AgentCardSource()
}

type AddAgentRequest_AgentCard struct {
	// The Agent Card to be added to the Stream
	AgentCard *AgentCard `protobuf:"bytes,5,opt,name=agent_card,json=agentCard,proto3,oneof"`
}

type AddAgentRequest_AgentCardUri struct {
	// The URI to the Agent Card to be added to the Stream.
	//
	// Both the URI field in the Stream as well as the Agent Card field,
	// fetched from the URI, will be populated.
	//
	// In the case that the URI is invalid, or permission is denied to access
	// the Agent Card, the method will fail
	AgentCardUri string `protobuf:"bytes,6,opt,name=agent_card_uri,json=agentCardUri,proto3,oneof"`
}

func (*AddAgentRequest_AgentCard) isAddAgentRequest_AgentCardSource() {}

func (*AddAgentRequest_AgentCardUri) isAddAgentRequest_AgentCardSource() {}

// Response message for AddAgent
type AddAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream that was created
	Stream        *Stream `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAgentResponse) Reset() {
	*x = AddAgentResponse{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgentResponse) ProtoMessage() {}

func (x *AddAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgentResponse.ProtoReflect.Descriptor instead.
func (*AddAgentResponse) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{7}
}

func (x *AddAgentResponse) GetStream() *Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

// Request message for InitialiseAgentFeedback
type InitialiseAgentFeedbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream target sets the expected behaviour of the Stream to create.
	// The resulting Stream will be created within either a new or existing idea,
	// or can be in the fulfilment of a context request.
	//
	// Types that are valid to be assigned to StreamTarget:
	//
	//	*InitialiseAgentFeedbackRequest_Account
	//	*InitialiseAgentFeedbackRequest_Idea
	//	*InitialiseAgentFeedbackRequest_Token
	StreamTarget isInitialiseAgentFeedbackRequest_StreamTarget `protobuf_oneof:"stream_target"`
	// Details about the agent interaction
	AgentInteraction *InitialiseAgentFeedbackRequest_AgentInteraction `protobuf:"bytes,5,opt,name=agent_interaction,json=agentInteraction,proto3" json:"agent_interaction,omitempty"`
	// Types that are valid to be assigned to FeedbackContent:
	//
	//	*InitialiseAgentFeedbackRequest_Note_
	//	*InitialiseAgentFeedbackRequest_AudioNote_
	//	*InitialiseAgentFeedbackRequest_MultiFileUpload_
	FeedbackContent isInitialiseAgentFeedbackRequest_FeedbackContent `protobuf_oneof:"feedback_content"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackRequest) Reset() {
	*x = InitialiseAgentFeedbackRequest{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackRequest) ProtoMessage() {}

func (x *InitialiseAgentFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackRequest.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{8}
}

func (x *InitialiseAgentFeedbackRequest) GetStreamTarget() isInitialiseAgentFeedbackRequest_StreamTarget {
	if x != nil {
		return x.StreamTarget
	}
	return nil
}

func (x *InitialiseAgentFeedbackRequest) GetAccount() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*InitialiseAgentFeedbackRequest_Account); ok {
			return x.Account
		}
	}
	return ""
}

func (x *InitialiseAgentFeedbackRequest) GetIdea() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*InitialiseAgentFeedbackRequest_Idea); ok {
			return x.Idea
		}
	}
	return ""
}

func (x *InitialiseAgentFeedbackRequest) GetToken() string {
	if x != nil {
		if x, ok := x.StreamTarget.(*InitialiseAgentFeedbackRequest_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *InitialiseAgentFeedbackRequest) GetAgentInteraction() *InitialiseAgentFeedbackRequest_AgentInteraction {
	if x != nil {
		return x.AgentInteraction
	}
	return nil
}

func (x *InitialiseAgentFeedbackRequest) GetFeedbackContent() isInitialiseAgentFeedbackRequest_FeedbackContent {
	if x != nil {
		return x.FeedbackContent
	}
	return nil
}

func (x *InitialiseAgentFeedbackRequest) GetNote() *InitialiseAgentFeedbackRequest_Note {
	if x != nil {
		if x, ok := x.FeedbackContent.(*InitialiseAgentFeedbackRequest_Note_); ok {
			return x.Note
		}
	}
	return nil
}

func (x *InitialiseAgentFeedbackRequest) GetAudioNote() *InitialiseAgentFeedbackRequest_AudioNote {
	if x != nil {
		if x, ok := x.FeedbackContent.(*InitialiseAgentFeedbackRequest_AudioNote_); ok {
			return x.AudioNote
		}
	}
	return nil
}

func (x *InitialiseAgentFeedbackRequest) GetMultiFileUpload() *InitialiseAgentFeedbackRequest_MultiFileUpload {
	if x != nil {
		if x, ok := x.FeedbackContent.(*InitialiseAgentFeedbackRequest_MultiFileUpload_); ok {
			return x.MultiFileUpload
		}
	}
	return nil
}

type isInitialiseAgentFeedbackRequest_StreamTarget interface {
	isInitialiseAgentFeedbackRequest_StreamTarget()
}

type InitialiseAgentFeedbackRequest_Account struct {
	// The Account that the Idea will be associated with.
	// Format: accounts/*
	//
	// Target: Create a new Idea, ie. do not add Stream to an existing Idea
	Account string `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type InitialiseAgentFeedbackRequest_Idea struct {
	// The Idea to add the Stream to. Will create if not specified.
	// Format: ideas/*
	//
	// Target: Add Stream to an existing Idea.
	Idea string `protobuf:"bytes,2,opt,name=idea,proto3,oneof"`
}

type InitialiseAgentFeedbackRequest_Token struct {
	// The token as part of the URL provided by the
	// GenerateProposalExecutionSignedUrl method.
	//
	// Format: `{payload}.{signature}`
	Token string `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

func (*InitialiseAgentFeedbackRequest_Account) isInitialiseAgentFeedbackRequest_StreamTarget() {}

func (*InitialiseAgentFeedbackRequest_Idea) isInitialiseAgentFeedbackRequest_StreamTarget() {}

func (*InitialiseAgentFeedbackRequest_Token) isInitialiseAgentFeedbackRequest_StreamTarget() {}

type isInitialiseAgentFeedbackRequest_FeedbackContent interface {
	isInitialiseAgentFeedbackRequest_FeedbackContent()
}

type InitialiseAgentFeedbackRequest_Note_ struct {
	// The text note feedback type
	Note *InitialiseAgentFeedbackRequest_Note `protobuf:"bytes,6,opt,name=note,proto3,oneof"`
}

type InitialiseAgentFeedbackRequest_AudioNote_ struct {
	// The audio note equivalent content
	AudioNote *InitialiseAgentFeedbackRequest_AudioNote `protobuf:"bytes,7,opt,name=audio_note,json=audioNote,proto3,oneof"`
}

type InitialiseAgentFeedbackRequest_MultiFileUpload_ struct {
	// The multi-file upload equivalent content
	MultiFileUpload *InitialiseAgentFeedbackRequest_MultiFileUpload `protobuf:"bytes,8,opt,name=multi_file_upload,json=multiFileUpload,proto3,oneof"`
}

func (*InitialiseAgentFeedbackRequest_Note_) isInitialiseAgentFeedbackRequest_FeedbackContent() {}

func (*InitialiseAgentFeedbackRequest_AudioNote_) isInitialiseAgentFeedbackRequest_FeedbackContent() {
}

func (*InitialiseAgentFeedbackRequest_MultiFileUpload_) isInitialiseAgentFeedbackRequest_FeedbackContent() {
}

// Response message for InitialiseAgentFeedback
type InitialiseAgentFeedbackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Stream that was created containing the agent feedback content
	ContentStream *Stream `protobuf:"bytes,1,opt,name=content_stream,json=contentStream,proto3" json:"content_stream,omitempty"`
	// The Agent type Stream that was created
	AgentStream *Stream `protobuf:"bytes,2,opt,name=agent_stream,json=agentStream,proto3" json:"agent_stream,omitempty"`
	// The response details in the case that additional action
	// is required: ie. upload the audio note or files
	//
	// Types that are valid to be assigned to ResponseDetails:
	//
	//	*InitialiseAgentFeedbackResponse_Note_
	//	*InitialiseAgentFeedbackResponse_AudioNote_
	//	*InitialiseAgentFeedbackResponse_MultiFileUpload_
	ResponseDetails isInitialiseAgentFeedbackResponse_ResponseDetails `protobuf_oneof:"response_details"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackResponse) Reset() {
	*x = InitialiseAgentFeedbackResponse{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackResponse) ProtoMessage() {}

func (x *InitialiseAgentFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackResponse.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{9}
}

func (x *InitialiseAgentFeedbackResponse) GetContentStream() *Stream {
	if x != nil {
		return x.ContentStream
	}
	return nil
}

func (x *InitialiseAgentFeedbackResponse) GetAgentStream() *Stream {
	if x != nil {
		return x.AgentStream
	}
	return nil
}

func (x *InitialiseAgentFeedbackResponse) GetResponseDetails() isInitialiseAgentFeedbackResponse_ResponseDetails {
	if x != nil {
		return x.ResponseDetails
	}
	return nil
}

func (x *InitialiseAgentFeedbackResponse) GetNote() *InitialiseAgentFeedbackResponse_Note {
	if x != nil {
		if x, ok := x.ResponseDetails.(*InitialiseAgentFeedbackResponse_Note_); ok {
			return x.Note
		}
	}
	return nil
}

func (x *InitialiseAgentFeedbackResponse) GetAudioNote() *InitialiseAgentFeedbackResponse_AudioNote {
	if x != nil {
		if x, ok := x.ResponseDetails.(*InitialiseAgentFeedbackResponse_AudioNote_); ok {
			return x.AudioNote
		}
	}
	return nil
}

func (x *InitialiseAgentFeedbackResponse) GetMultiFileUpload() *InitialiseAgentFeedbackResponse_MultiFileUpload {
	if x != nil {
		if x, ok := x.ResponseDetails.(*InitialiseAgentFeedbackResponse_MultiFileUpload_); ok {
			return x.MultiFileUpload
		}
	}
	return nil
}

type isInitialiseAgentFeedbackResponse_ResponseDetails interface {
	isInitialiseAgentFeedbackResponse_ResponseDetails()
}

type InitialiseAgentFeedbackResponse_Note_ struct {
	// The text note feedback response
	Note *InitialiseAgentFeedbackResponse_Note `protobuf:"bytes,3,opt,name=note,proto3,oneof"`
}

type InitialiseAgentFeedbackResponse_AudioNote_ struct {
	// Details for uploading the audio note
	AudioNote *InitialiseAgentFeedbackResponse_AudioNote `protobuf:"bytes,4,opt,name=audio_note,json=audioNote,proto3,oneof"`
}

type InitialiseAgentFeedbackResponse_MultiFileUpload_ struct {
	// The multi-file upload equivalent content
	MultiFileUpload *InitialiseAgentFeedbackResponse_MultiFileUpload `protobuf:"bytes,5,opt,name=multi_file_upload,json=multiFileUpload,proto3,oneof"`
}

func (*InitialiseAgentFeedbackResponse_Note_) isInitialiseAgentFeedbackResponse_ResponseDetails() {}

func (*InitialiseAgentFeedbackResponse_AudioNote_) isInitialiseAgentFeedbackResponse_ResponseDetails() {
}

func (*InitialiseAgentFeedbackResponse_MultiFileUpload_) isInitialiseAgentFeedbackResponse_ResponseDetails() {
}

// Request message for TestIdeateAccess
type TestIdeateAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account to test access for
	// Format: accounts/*
	Account       string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIdeateAccessRequest) Reset() {
	*x = TestIdeateAccessRequest{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIdeateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIdeateAccessRequest) ProtoMessage() {}

func (x *TestIdeateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIdeateAccessRequest.ProtoReflect.Descriptor instead.
func (*TestIdeateAccessRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{10}
}

func (x *TestIdeateAccessRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// Response message for TestIdeateAccess
type TestIdeateAccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the account has any restrictions
	Restriction   TestIdeateAccessResponse_Restriction `protobuf:"varint,1,opt,name=restriction,proto3,enum=alis.ideate.TestIdeateAccessResponse_Restriction" json:"restriction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIdeateAccessResponse) Reset() {
	*x = TestIdeateAccessResponse{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIdeateAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIdeateAccessResponse) ProtoMessage() {}

func (x *TestIdeateAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIdeateAccessResponse.ProtoReflect.Descriptor instead.
func (*TestIdeateAccessResponse) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{11}
}

func (x *TestIdeateAccessResponse) GetRestriction() TestIdeateAccessResponse_Restriction {
	if x != nil {
		return x.Restriction
	}
	return TestIdeateAccessResponse_RESTRICTION_UNSPECIFIED
}

// A file to be uploaded
type AddMultiFileUploadRequest_File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The filename of the file that will be uploaded
	// Example: my-data.xlsx
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// The file content type
	// (https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5) For
	// example: image/png If an object is stored without a Content-Type, it is
	// served as application/octet-stream.
	MimeType      string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMultiFileUploadRequest_File) Reset() {
	*x = AddMultiFileUploadRequest_File{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMultiFileUploadRequest_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMultiFileUploadRequest_File) ProtoMessage() {}

func (x *AddMultiFileUploadRequest_File) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMultiFileUploadRequest_File.ProtoReflect.Descriptor instead.
func (*AddMultiFileUploadRequest_File) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{4, 0}
}

func (x *AddMultiFileUploadRequest_File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AddMultiFileUploadRequest_File) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// The link that can be used to upload the file to.
type AddMultiFileUploadResponse_File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The filename of the file that will be uploaded
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// The file content type
	// (https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5) For
	// example: image/png If an object is stored without a Content-Type, it is
	// served as application/octet-stream.
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// The upload link for the corresponding filename
	UploadUri     string `protobuf:"bytes,3,opt,name=upload_uri,json=uploadUri,proto3" json:"upload_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMultiFileUploadResponse_File) Reset() {
	*x = AddMultiFileUploadResponse_File{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMultiFileUploadResponse_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMultiFileUploadResponse_File) ProtoMessage() {}

func (x *AddMultiFileUploadResponse_File) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMultiFileUploadResponse_File.ProtoReflect.Descriptor instead.
func (*AddMultiFileUploadResponse_File) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{5, 0}
}

func (x *AddMultiFileUploadResponse_File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AddMultiFileUploadResponse_File) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AddMultiFileUploadResponse_File) GetUploadUri() string {
	if x != nil {
		return x.UploadUri
	}
	return ""
}

// Definition of AgentInteraction
type InitialiseAgentFeedbackRequest_AgentInteraction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Agent Stream requires an Agent Card to be
	// added to it. This can be done in one of two ways:
	// 1. By providing an Agent Card directly
	// 2. By providing a URI to an Agent Card
	//
	// Types that are valid to be assigned to AgentCardSource:
	//
	//	*InitialiseAgentFeedbackRequest_AgentInteraction_AgentCard
	//	*InitialiseAgentFeedbackRequest_AgentInteraction_AgentCardUri
	AgentCardSource isInitialiseAgentFeedbackRequest_AgentInteraction_AgentCardSource `protobuf_oneof:"agent_card_source"`
	// The conversation history with the agent.
	// A JSON representation of the conversation history
	// can be provided.
	ConversationHistory string `protobuf:"bytes,3,opt,name=conversation_history,json=conversationHistory,proto3" json:"conversation_history,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackRequest_AgentInteraction) Reset() {
	*x = InitialiseAgentFeedbackRequest_AgentInteraction{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackRequest_AgentInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackRequest_AgentInteraction) ProtoMessage() {}

func (x *InitialiseAgentFeedbackRequest_AgentInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackRequest_AgentInteraction.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackRequest_AgentInteraction) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{8, 0}
}

func (x *InitialiseAgentFeedbackRequest_AgentInteraction) GetAgentCardSource() isInitialiseAgentFeedbackRequest_AgentInteraction_AgentCardSource {
	if x != nil {
		return x.AgentCardSource
	}
	return nil
}

func (x *InitialiseAgentFeedbackRequest_AgentInteraction) GetAgentCard() *AgentCard {
	if x != nil {
		if x, ok := x.AgentCardSource.(*InitialiseAgentFeedbackRequest_AgentInteraction_AgentCard); ok {
			return x.AgentCard
		}
	}
	return nil
}

func (x *InitialiseAgentFeedbackRequest_AgentInteraction) GetAgentCardUri() string {
	if x != nil {
		if x, ok := x.AgentCardSource.(*InitialiseAgentFeedbackRequest_AgentInteraction_AgentCardUri); ok {
			return x.AgentCardUri
		}
	}
	return ""
}

func (x *InitialiseAgentFeedbackRequest_AgentInteraction) GetConversationHistory() string {
	if x != nil {
		return x.ConversationHistory
	}
	return ""
}

type isInitialiseAgentFeedbackRequest_AgentInteraction_AgentCardSource interface {
	isInitialiseAgentFeedbackRequest_AgentInteraction_AgentCardSource()
}

type InitialiseAgentFeedbackRequest_AgentInteraction_AgentCard struct {
	// The Agent Card to be added to the Stream
	AgentCard *AgentCard `protobuf:"bytes,1,opt,name=agent_card,json=agentCard,proto3,oneof"`
}

type InitialiseAgentFeedbackRequest_AgentInteraction_AgentCardUri struct {
	// The URI to the Agent Card to be added to the Stream.
	//
	// Both the URI field in the Stream as well as the Agent Card field,
	// fetched from the URI, will be populated.
	//
	// In the case that the URI is invalid, or permission is denied to access
	// the Agent Card, the method will fail
	AgentCardUri string `protobuf:"bytes,2,opt,name=agent_card_uri,json=agentCardUri,proto3,oneof"`
}

func (*InitialiseAgentFeedbackRequest_AgentInteraction_AgentCard) isInitialiseAgentFeedbackRequest_AgentInteraction_AgentCardSource() {
}

func (*InitialiseAgentFeedbackRequest_AgentInteraction_AgentCardUri) isInitialiseAgentFeedbackRequest_AgentInteraction_AgentCardSource() {
}

// Definition of the Note
type InitialiseAgentFeedbackRequest_Note struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content of the note to be added to the Stream
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackRequest_Note) Reset() {
	*x = InitialiseAgentFeedbackRequest_Note{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackRequest_Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackRequest_Note) ProtoMessage() {}

func (x *InitialiseAgentFeedbackRequest_Note) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackRequest_Note.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackRequest_Note) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{8, 1}
}

func (x *InitialiseAgentFeedbackRequest_Note) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Definition of AudioNote
type InitialiseAgentFeedbackRequest_AudioNote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The MIME type of the audio note
	// supports all 'audio/*' types
	MimeType      string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackRequest_AudioNote) Reset() {
	*x = InitialiseAgentFeedbackRequest_AudioNote{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackRequest_AudioNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackRequest_AudioNote) ProtoMessage() {}

func (x *InitialiseAgentFeedbackRequest_AudioNote) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackRequest_AudioNote.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackRequest_AudioNote) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{8, 2}
}

func (x *InitialiseAgentFeedbackRequest_AudioNote) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// Definition of MultiFileUpload
type InitialiseAgentFeedbackRequest_MultiFileUpload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A note added for context, in valid markdown
	Note string `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	// The set of files to upload
	Files         []*InitialiseAgentFeedbackRequest_MultiFileUpload_File `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload) Reset() {
	*x = InitialiseAgentFeedbackRequest_MultiFileUpload{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackRequest_MultiFileUpload) ProtoMessage() {}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackRequest_MultiFileUpload.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackRequest_MultiFileUpload) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{8, 3}
}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload) GetFiles() []*InitialiseAgentFeedbackRequest_MultiFileUpload_File {
	if x != nil {
		return x.Files
	}
	return nil
}

// A file to be uploaded
type InitialiseAgentFeedbackRequest_MultiFileUpload_File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The filename of the file that will be uploaded
	// Example: my-data.xlsx
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// The file content type
	// (https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5) For
	// example: image/png If an object is stored without a Content-Type, it is
	// served as application/octet-stream.
	MimeType      string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload_File) Reset() {
	*x = InitialiseAgentFeedbackRequest_MultiFileUpload_File{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackRequest_MultiFileUpload_File) ProtoMessage() {}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload_File) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackRequest_MultiFileUpload_File.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackRequest_MultiFileUpload_File) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{8, 3, 0}
}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload_File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InitialiseAgentFeedbackRequest_MultiFileUpload_File) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// Definition of Note response
// Will always just be empty.
type InitialiseAgentFeedbackResponse_Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackResponse_Note) Reset() {
	*x = InitialiseAgentFeedbackResponse_Note{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackResponse_Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackResponse_Note) ProtoMessage() {}

func (x *InitialiseAgentFeedbackResponse_Note) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackResponse_Note.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackResponse_Note) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{9, 0}
}

// Definition of AudioNote
type InitialiseAgentFeedbackResponse_AudioNote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The link that can be used to upload the audio note to.
	UploadUri     string `protobuf:"bytes,2,opt,name=upload_uri,json=uploadUri,proto3" json:"upload_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackResponse_AudioNote) Reset() {
	*x = InitialiseAgentFeedbackResponse_AudioNote{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackResponse_AudioNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackResponse_AudioNote) ProtoMessage() {}

func (x *InitialiseAgentFeedbackResponse_AudioNote) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackResponse_AudioNote.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackResponse_AudioNote) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{9, 1}
}

func (x *InitialiseAgentFeedbackResponse_AudioNote) GetUploadUri() string {
	if x != nil {
		return x.UploadUri
	}
	return ""
}

// Definition of MultiFileUpload
type InitialiseAgentFeedbackResponse_MultiFileUpload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The set of files and their upload urls
	Files         []*InitialiseAgentFeedbackResponse_MultiFileUpload_File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload) Reset() {
	*x = InitialiseAgentFeedbackResponse_MultiFileUpload{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackResponse_MultiFileUpload) ProtoMessage() {}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackResponse_MultiFileUpload.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackResponse_MultiFileUpload) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{9, 2}
}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload) GetFiles() []*InitialiseAgentFeedbackResponse_MultiFileUpload_File {
	if x != nil {
		return x.Files
	}
	return nil
}

// The link that can be used to upload the file to.
type InitialiseAgentFeedbackResponse_MultiFileUpload_File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The filename of the file that will be uploaded
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// The file content type
	// (https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5) For
	// example: image/png If an object is stored without a Content-Type, it is
	// served as application/octet-stream.
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// The upload link for the corresponding filename
	UploadUri     string `protobuf:"bytes,3,opt,name=upload_uri,json=uploadUri,proto3" json:"upload_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload_File) Reset() {
	*x = InitialiseAgentFeedbackResponse_MultiFileUpload_File{}
	mi := &file_alis_ideate_ideate_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAgentFeedbackResponse_MultiFileUpload_File) ProtoMessage() {}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload_File) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_ideate_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAgentFeedbackResponse_MultiFileUpload_File.ProtoReflect.Descriptor instead.
func (*InitialiseAgentFeedbackResponse_MultiFileUpload_File) Descriptor() ([]byte, []int) {
	return file_alis_ideate_ideate_proto_rawDescGZIP(), []int{9, 2, 0}
}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload_File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload_File) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *InitialiseAgentFeedbackResponse_MultiFileUpload_File) GetUploadUri() string {
	if x != nil {
		return x.UploadUri
	}
	return ""
}

var File_alis_ideate_ideate_proto protoreflect.FileDescriptor

const file_alis_ideate_ideate_proto_rawDesc = "" +
	"\n" +
	"\x18alis/ideate/ideate.proto\x12\valis.ideate\x1a google/protobuf/field_mask.proto\x1a#google/longrunning/operations.proto\x1a\x1calis/ideate/agent_card.proto\x1a\x16alis/ideate/idea.proto\x1a\x16alis/ideate/spec.proto\x1a\x18alis/ideate/stream.proto\"\xba\x01\n" +
	"\x0eAddNoteRequest\x12\x1a\n" +
	"\aaccount\x18\x01 \x01(\tH\x00R\aaccount\x12\x14\n" +
	"\x04idea\x18\x02 \x01(\tH\x00R\x04idea\x12\x16\n" +
	"\x05token\x18\x03 \x01(\tH\x00R\x05token\x123\n" +
	"\x14contribution_session\x18\x04 \x01(\tH\x00R\x13contributionSession\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontentB\x0f\n" +
	"\rstream_target\">\n" +
	"\x0fAddNoteResponse\x12+\n" +
	"\x06stream\x18\x01 \x01(\v2\x13.alis.ideate.StreamR\x06stream\"\xe1\x01\n" +
	"\x13AddAudioNoteRequest\x12\x1a\n" +
	"\aaccount\x18\x01 \x01(\tH\x00R\aaccount\x12\x14\n" +
	"\x04idea\x18\x02 \x01(\tH\x00R\x04idea\x12\x16\n" +
	"\x05token\x18\x03 \x01(\tH\x00R\x05token\x123\n" +
	"\x14contribution_session\x18\x04 \x01(\tH\x00R\x13contributionSession\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"origin_uri\x18\x06 \x01(\tR\toriginUriB\x0f\n" +
	"\rstream_target\"b\n" +
	"\x14AddAudioNoteResponse\x12+\n" +
	"\x06stream\x18\x01 \x01(\v2\x13.alis.ideate.StreamR\x06stream\x12\x1d\n" +
	"\n" +
	"upload_uri\x18\x02 \x01(\tR\tuploadUri\"\xe2\x02\n" +
	"\x19AddMultiFileUploadRequest\x12\x1a\n" +
	"\aaccount\x18\x01 \x01(\tH\x00R\aaccount\x12\x14\n" +
	"\x04idea\x18\x02 \x01(\tH\x00R\x04idea\x12\x16\n" +
	"\x05token\x18\x03 \x01(\tH\x00R\x05token\x123\n" +
	"\x14contribution_session\x18\x04 \x01(\tH\x00R\x13contributionSession\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12A\n" +
	"\x05files\x18\x06 \x03(\v2+.alis.ideate.AddMultiFileUploadRequest.FileR\x05files\x12\x1d\n" +
	"\n" +
	"origin_uri\x18\a \x01(\tR\toriginUri\x1a?\n" +
	"\x04File\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeTypeB\x0f\n" +
	"\rstream_target\"\xed\x01\n" +
	"\x1aAddMultiFileUploadResponse\x12+\n" +
	"\x06stream\x18\x01 \x01(\v2\x13.alis.ideate.StreamR\x06stream\x12B\n" +
	"\x05files\x18\x02 \x03(\v2,.alis.ideate.AddMultiFileUploadResponse.FileR\x05files\x1a^\n" +
	"\x04File\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"upload_uri\x18\x03 \x01(\tR\tuploadUri\"\x97\x02\n" +
	"\x0fAddAgentRequest\x12\x1a\n" +
	"\aaccount\x18\x01 \x01(\tH\x00R\aaccount\x12\x14\n" +
	"\x04idea\x18\x02 \x01(\tH\x00R\x04idea\x12\x16\n" +
	"\x05token\x18\x03 \x01(\tH\x00R\x05token\x123\n" +
	"\x14contribution_session\x18\x04 \x01(\tH\x00R\x13contributionSession\x127\n" +
	"\n" +
	"agent_card\x18\x05 \x01(\v2\x16.alis.ideate.AgentCardH\x01R\tagentCard\x12&\n" +
	"\x0eagent_card_uri\x18\x06 \x01(\tH\x01R\fagentCardUriB\x0f\n" +
	"\rstream_targetB\x13\n" +
	"\x11agent_card_source\"?\n" +
	"\x10AddAgentResponse\x12+\n" +
	"\x06stream\x18\x01 \x01(\v2\x13.alis.ideate.StreamR\x06stream\"\xd0\a\n" +
	"\x1eInitialiseAgentFeedbackRequest\x12\x1a\n" +
	"\aaccount\x18\x01 \x01(\tH\x00R\aaccount\x12\x14\n" +
	"\x04idea\x18\x02 \x01(\tH\x00R\x04idea\x12\x16\n" +
	"\x05token\x18\x03 \x01(\tH\x00R\x05token\x12i\n" +
	"\x11agent_interaction\x18\x05 \x01(\v2<.alis.ideate.InitialiseAgentFeedbackRequest.AgentInteractionR\x10agentInteraction\x12F\n" +
	"\x04note\x18\x06 \x01(\v20.alis.ideate.InitialiseAgentFeedbackRequest.NoteH\x01R\x04note\x12V\n" +
	"\n" +
	"audio_note\x18\a \x01(\v25.alis.ideate.InitialiseAgentFeedbackRequest.AudioNoteH\x01R\taudioNote\x12i\n" +
	"\x11multi_file_upload\x18\b \x01(\v2;.alis.ideate.InitialiseAgentFeedbackRequest.MultiFileUploadH\x01R\x0fmultiFileUpload\x1a\xbb\x01\n" +
	"\x10AgentInteraction\x127\n" +
	"\n" +
	"agent_card\x18\x01 \x01(\v2\x16.alis.ideate.AgentCardH\x00R\tagentCard\x12&\n" +
	"\x0eagent_card_uri\x18\x02 \x01(\tH\x00R\fagentCardUri\x121\n" +
	"\x14conversation_history\x18\x03 \x01(\tR\x13conversationHistoryB\x13\n" +
	"\x11agent_card_source\x1a \n" +
	"\x04Note\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a(\n" +
	"\tAudioNote\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x1a\xbe\x01\n" +
	"\x0fMultiFileUpload\x12\x12\n" +
	"\x04note\x18\x01 \x01(\tR\x04note\x12V\n" +
	"\x05files\x18\x02 \x03(\v2@.alis.ideate.InitialiseAgentFeedbackRequest.MultiFileUpload.FileR\x05files\x1a?\n" +
	"\x04File\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeTypeB\x0f\n" +
	"\rstream_targetB\x12\n" +
	"\x10feedback_content\"\xb8\x05\n" +
	"\x1fInitialiseAgentFeedbackResponse\x12:\n" +
	"\x0econtent_stream\x18\x01 \x01(\v2\x13.alis.ideate.StreamR\rcontentStream\x126\n" +
	"\fagent_stream\x18\x02 \x01(\v2\x13.alis.ideate.StreamR\vagentStream\x12G\n" +
	"\x04note\x18\x03 \x01(\v21.alis.ideate.InitialiseAgentFeedbackResponse.NoteH\x00R\x04note\x12W\n" +
	"\n" +
	"audio_note\x18\x04 \x01(\v26.alis.ideate.InitialiseAgentFeedbackResponse.AudioNoteH\x00R\taudioNote\x12j\n" +
	"\x11multi_file_upload\x18\x05 \x01(\v2<.alis.ideate.InitialiseAgentFeedbackResponse.MultiFileUploadH\x00R\x0fmultiFileUpload\x1a\x06\n" +
	"\x04Note\x1a*\n" +
	"\tAudioNote\x12\x1d\n" +
	"\n" +
	"upload_uri\x18\x02 \x01(\tR\tuploadUri\x1a\xca\x01\n" +
	"\x0fMultiFileUpload\x12W\n" +
	"\x05files\x18\x01 \x03(\v2A.alis.ideate.InitialiseAgentFeedbackResponse.MultiFileUpload.FileR\x05files\x1a^\n" +
	"\x04File\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"upload_uri\x18\x03 \x01(\tR\tuploadUriB\x12\n" +
	"\x10response_details\"3\n" +
	"\x17TestIdeateAccessRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"\xd4\x01\n" +
	"\x18TestIdeateAccessResponse\x12S\n" +
	"\vrestriction\x18\x01 \x01(\x0e21.alis.ideate.TestIdeateAccessResponse.RestrictionR\vrestriction\"c\n" +
	"\vRestriction\x12\x1b\n" +
	"\x17RESTRICTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aNO_SEAT\x10\x01\x12\x11\n" +
	"\rTRIAL_EXPIRED\x10\x02\x12\x17\n" +
	"\x13PLAN_LIMITS_REACHED\x10\x032\xa3\b\n" +
	"\rIdeateService\x12F\n" +
	"\aAddNote\x12\x1b.alis.ideate.AddNoteRequest\x1a\x1c.alis.ideate.AddNoteResponse\"\x00\x12U\n" +
	"\fAddAudioNote\x12 .alis.ideate.AddAudioNoteRequest\x1a!.alis.ideate.AddAudioNoteResponse\"\x00\x12g\n" +
	"\x12AddMultiFileUpload\x12&.alis.ideate.AddMultiFileUploadRequest\x1a'.alis.ideate.AddMultiFileUploadResponse\"\x00\x12I\n" +
	"\bAddAgent\x12\x1c.alis.ideate.AddAgentRequest\x1a\x1d.alis.ideate.AddAgentResponse\"\x00\x12v\n" +
	"\x17InitialiseAgentFeedback\x12+.alis.ideate.InitialiseAgentFeedbackRequest\x1a,.alis.ideate.InitialiseAgentFeedbackResponse\"\x00\x12;\n" +
	"\aGetIdea\x12\x1b.alis.ideate.GetIdeaRequest\x1a\x11.alis.ideate.Idea\"\x00\x12A\n" +
	"\tGetStream\x12\x1d.alis.ideate.GetStreamRequest\x1a\x13.alis.ideate.Stream\"\x00\x12;\n" +
	"\aGetSpec\x12\x1b.alis.ideate.GetSpecRequest\x1a\x11.alis.ideate.Spec\"\x00\x12d\n" +
	"\x11RetrieveIdeaSpecs\x12%.alis.ideate.RetrieveIdeaSpecsRequest\x1a&.alis.ideate.RetrieveIdeaSpecsResponse\"\x00\x12g\n" +
	"\x17GenerateCustomAgentSpec\x12+.alis.ideate.GenerateCustomAgentSpecRequest\x1a\x1d.google.longrunning.Operation\"\x00\x12a\n" +
	"\x10TestIdeateAccess\x12$.alis.ideate.TestIdeateAccessRequest\x1a%.alis.ideate.TestIdeateAccessResponse\"\x00\x12X\n" +
	"\fGetOperation\x12'.google.longrunning.GetOperationRequest\x1a\x1d.google.longrunning.Operation\"\x00B0Z.github.com/alis-exchange/ideate-go/alis/ideateb\x06proto3"

var (
	file_alis_ideate_ideate_proto_rawDescOnce sync.Once
	file_alis_ideate_ideate_proto_rawDescData []byte
)

func file_alis_ideate_ideate_proto_rawDescGZIP() []byte {
	file_alis_ideate_ideate_proto_rawDescOnce.Do(func() {
		file_alis_ideate_ideate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_ideate_ideate_proto_rawDesc), len(file_alis_ideate_ideate_proto_rawDesc)))
	})
	return file_alis_ideate_ideate_proto_rawDescData
}

var file_alis_ideate_ideate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alis_ideate_ideate_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_alis_ideate_ideate_proto_goTypes = []any{
	(TestIdeateAccessResponse_Restriction)(0),                    // 0: alis.ideate.TestIdeateAccessResponse.Restriction
	(*AddNoteRequest)(nil),                                       // 1: alis.ideate.AddNoteRequest
	(*AddNoteResponse)(nil),                                      // 2: alis.ideate.AddNoteResponse
	(*AddAudioNoteRequest)(nil),                                  // 3: alis.ideate.AddAudioNoteRequest
	(*AddAudioNoteResponse)(nil),                                 // 4: alis.ideate.AddAudioNoteResponse
	(*AddMultiFileUploadRequest)(nil),                            // 5: alis.ideate.AddMultiFileUploadRequest
	(*AddMultiFileUploadResponse)(nil),                           // 6: alis.ideate.AddMultiFileUploadResponse
	(*AddAgentRequest)(nil),                                      // 7: alis.ideate.AddAgentRequest
	(*AddAgentResponse)(nil),                                     // 8: alis.ideate.AddAgentResponse
	(*InitialiseAgentFeedbackRequest)(nil),                       // 9: alis.ideate.InitialiseAgentFeedbackRequest
	(*InitialiseAgentFeedbackResponse)(nil),                      // 10: alis.ideate.InitialiseAgentFeedbackResponse
	(*TestIdeateAccessRequest)(nil),                              // 11: alis.ideate.TestIdeateAccessRequest
	(*TestIdeateAccessResponse)(nil),                             // 12: alis.ideate.TestIdeateAccessResponse
	(*AddMultiFileUploadRequest_File)(nil),                       // 13: alis.ideate.AddMultiFileUploadRequest.File
	(*AddMultiFileUploadResponse_File)(nil),                      // 14: alis.ideate.AddMultiFileUploadResponse.File
	(*InitialiseAgentFeedbackRequest_AgentInteraction)(nil),      // 15: alis.ideate.InitialiseAgentFeedbackRequest.AgentInteraction
	(*InitialiseAgentFeedbackRequest_Note)(nil),                  // 16: alis.ideate.InitialiseAgentFeedbackRequest.Note
	(*InitialiseAgentFeedbackRequest_AudioNote)(nil),             // 17: alis.ideate.InitialiseAgentFeedbackRequest.AudioNote
	(*InitialiseAgentFeedbackRequest_MultiFileUpload)(nil),       // 18: alis.ideate.InitialiseAgentFeedbackRequest.MultiFileUpload
	(*InitialiseAgentFeedbackRequest_MultiFileUpload_File)(nil),  // 19: alis.ideate.InitialiseAgentFeedbackRequest.MultiFileUpload.File
	(*InitialiseAgentFeedbackResponse_Note)(nil),                 // 20: alis.ideate.InitialiseAgentFeedbackResponse.Note
	(*InitialiseAgentFeedbackResponse_AudioNote)(nil),            // 21: alis.ideate.InitialiseAgentFeedbackResponse.AudioNote
	(*InitialiseAgentFeedbackResponse_MultiFileUpload)(nil),      // 22: alis.ideate.InitialiseAgentFeedbackResponse.MultiFileUpload
	(*InitialiseAgentFeedbackResponse_MultiFileUpload_File)(nil), // 23: alis.ideate.InitialiseAgentFeedbackResponse.MultiFileUpload.File
	(*Stream)(nil),                          // 24: alis.ideate.Stream
	(*AgentCard)(nil),                       // 25: alis.ideate.AgentCard
	(*GetIdeaRequest)(nil),                  // 26: alis.ideate.GetIdeaRequest
	(*GetStreamRequest)(nil),                // 27: alis.ideate.GetStreamRequest
	(*GetSpecRequest)(nil),                  // 28: alis.ideate.GetSpecRequest
	(*RetrieveIdeaSpecsRequest)(nil),        // 29: alis.ideate.RetrieveIdeaSpecsRequest
	(*GenerateCustomAgentSpecRequest)(nil),  // 30: alis.ideate.GenerateCustomAgentSpecRequest
	(*longrunning.GetOperationRequest)(nil), // 31: google.longrunning.GetOperationRequest
	(*Idea)(nil),                            // 32: alis.ideate.Idea
	(*Spec)(nil),                            // 33: alis.ideate.Spec
	(*RetrieveIdeaSpecsResponse)(nil),       // 34: alis.ideate.RetrieveIdeaSpecsResponse
	(*longrunning.Operation)(nil),           // 35: google.longrunning.Operation
}
var file_alis_ideate_ideate_proto_depIdxs = []int32{
	24, // 0: alis.ideate.AddNoteResponse.stream:type_name -> alis.ideate.Stream
	24, // 1: alis.ideate.AddAudioNoteResponse.stream:type_name -> alis.ideate.Stream
	13, // 2: alis.ideate.AddMultiFileUploadRequest.files:type_name -> alis.ideate.AddMultiFileUploadRequest.File
	24, // 3: alis.ideate.AddMultiFileUploadResponse.stream:type_name -> alis.ideate.Stream
	14, // 4: alis.ideate.AddMultiFileUploadResponse.files:type_name -> alis.ideate.AddMultiFileUploadResponse.File
	25, // 5: alis.ideate.AddAgentRequest.agent_card:type_name -> alis.ideate.AgentCard
	24, // 6: alis.ideate.AddAgentResponse.stream:type_name -> alis.ideate.Stream
	15, // 7: alis.ideate.InitialiseAgentFeedbackRequest.agent_interaction:type_name -> alis.ideate.InitialiseAgentFeedbackRequest.AgentInteraction
	16, // 8: alis.ideate.InitialiseAgentFeedbackRequest.note:type_name -> alis.ideate.InitialiseAgentFeedbackRequest.Note
	17, // 9: alis.ideate.InitialiseAgentFeedbackRequest.audio_note:type_name -> alis.ideate.InitialiseAgentFeedbackRequest.AudioNote
	18, // 10: alis.ideate.InitialiseAgentFeedbackRequest.multi_file_upload:type_name -> alis.ideate.InitialiseAgentFeedbackRequest.MultiFileUpload
	24, // 11: alis.ideate.InitialiseAgentFeedbackResponse.content_stream:type_name -> alis.ideate.Stream
	24, // 12: alis.ideate.InitialiseAgentFeedbackResponse.agent_stream:type_name -> alis.ideate.Stream
	20, // 13: alis.ideate.InitialiseAgentFeedbackResponse.note:type_name -> alis.ideate.InitialiseAgentFeedbackResponse.Note
	21, // 14: alis.ideate.InitialiseAgentFeedbackResponse.audio_note:type_name -> alis.ideate.InitialiseAgentFeedbackResponse.AudioNote
	22, // 15: alis.ideate.InitialiseAgentFeedbackResponse.multi_file_upload:type_name -> alis.ideate.InitialiseAgentFeedbackResponse.MultiFileUpload
	0,  // 16: alis.ideate.TestIdeateAccessResponse.restriction:type_name -> alis.ideate.TestIdeateAccessResponse.Restriction
	25, // 17: alis.ideate.InitialiseAgentFeedbackRequest.AgentInteraction.agent_card:type_name -> alis.ideate.AgentCard
	19, // 18: alis.ideate.InitialiseAgentFeedbackRequest.MultiFileUpload.files:type_name -> alis.ideate.InitialiseAgentFeedbackRequest.MultiFileUpload.File
	23, // 19: alis.ideate.InitialiseAgentFeedbackResponse.MultiFileUpload.files:type_name -> alis.ideate.InitialiseAgentFeedbackResponse.MultiFileUpload.File
	1,  // 20: alis.ideate.IdeateService.AddNote:input_type -> alis.ideate.AddNoteRequest
	3,  // 21: alis.ideate.IdeateService.AddAudioNote:input_type -> alis.ideate.AddAudioNoteRequest
	5,  // 22: alis.ideate.IdeateService.AddMultiFileUpload:input_type -> alis.ideate.AddMultiFileUploadRequest
	7,  // 23: alis.ideate.IdeateService.AddAgent:input_type -> alis.ideate.AddAgentRequest
	9,  // 24: alis.ideate.IdeateService.InitialiseAgentFeedback:input_type -> alis.ideate.InitialiseAgentFeedbackRequest
	26, // 25: alis.ideate.IdeateService.GetIdea:input_type -> alis.ideate.GetIdeaRequest
	27, // 26: alis.ideate.IdeateService.GetStream:input_type -> alis.ideate.GetStreamRequest
	28, // 27: alis.ideate.IdeateService.GetSpec:input_type -> alis.ideate.GetSpecRequest
	29, // 28: alis.ideate.IdeateService.RetrieveIdeaSpecs:input_type -> alis.ideate.RetrieveIdeaSpecsRequest
	30, // 29: alis.ideate.IdeateService.GenerateCustomAgentSpec:input_type -> alis.ideate.GenerateCustomAgentSpecRequest
	11, // 30: alis.ideate.IdeateService.TestIdeateAccess:input_type -> alis.ideate.TestIdeateAccessRequest
	31, // 31: alis.ideate.IdeateService.GetOperation:input_type -> google.longrunning.GetOperationRequest
	2,  // 32: alis.ideate.IdeateService.AddNote:output_type -> alis.ideate.AddNoteResponse
	4,  // 33: alis.ideate.IdeateService.AddAudioNote:output_type -> alis.ideate.AddAudioNoteResponse
	6,  // 34: alis.ideate.IdeateService.AddMultiFileUpload:output_type -> alis.ideate.AddMultiFileUploadResponse
	8,  // 35: alis.ideate.IdeateService.AddAgent:output_type -> alis.ideate.AddAgentResponse
	10, // 36: alis.ideate.IdeateService.InitialiseAgentFeedback:output_type -> alis.ideate.InitialiseAgentFeedbackResponse
	32, // 37: alis.ideate.IdeateService.GetIdea:output_type -> alis.ideate.Idea
	24, // 38: alis.ideate.IdeateService.GetStream:output_type -> alis.ideate.Stream
	33, // 39: alis.ideate.IdeateService.GetSpec:output_type -> alis.ideate.Spec
	34, // 40: alis.ideate.IdeateService.RetrieveIdeaSpecs:output_type -> alis.ideate.RetrieveIdeaSpecsResponse
	35, // 41: alis.ideate.IdeateService.GenerateCustomAgentSpec:output_type -> google.longrunning.Operation
	12, // 42: alis.ideate.IdeateService.TestIdeateAccess:output_type -> alis.ideate.TestIdeateAccessResponse
	35, // 43: alis.ideate.IdeateService.GetOperation:output_type -> google.longrunning.Operation
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_alis_ideate_ideate_proto_init() }
func file_alis_ideate_ideate_proto_init() {
	if File_alis_ideate_ideate_proto != nil {
		return
	}
	file_alis_ideate_agent_card_proto_init()
	file_alis_ideate_idea_proto_init()
	file_alis_ideate_spec_proto_init()
	file_alis_ideate_stream_proto_init()
	file_alis_ideate_ideate_proto_msgTypes[0].OneofWrappers = []any{
		(*AddNoteRequest_Account)(nil),
		(*AddNoteRequest_Idea)(nil),
		(*AddNoteRequest_Token)(nil),
		(*AddNoteRequest_ContributionSession)(nil),
	}
	file_alis_ideate_ideate_proto_msgTypes[2].OneofWrappers = []any{
		(*AddAudioNoteRequest_Account)(nil),
		(*AddAudioNoteRequest_Idea)(nil),
		(*AddAudioNoteRequest_Token)(nil),
		(*AddAudioNoteRequest_ContributionSession)(nil),
	}
	file_alis_ideate_ideate_proto_msgTypes[4].OneofWrappers = []any{
		(*AddMultiFileUploadRequest_Account)(nil),
		(*AddMultiFileUploadRequest_Idea)(nil),
		(*AddMultiFileUploadRequest_Token)(nil),
		(*AddMultiFileUploadRequest_ContributionSession)(nil),
	}
	file_alis_ideate_ideate_proto_msgTypes[6].OneofWrappers = []any{
		(*AddAgentRequest_Account)(nil),
		(*AddAgentRequest_Idea)(nil),
		(*AddAgentRequest_Token)(nil),
		(*AddAgentRequest_ContributionSession)(nil),
		(*AddAgentRequest_AgentCard)(nil),
		(*AddAgentRequest_AgentCardUri)(nil),
	}
	file_alis_ideate_ideate_proto_msgTypes[8].OneofWrappers = []any{
		(*InitialiseAgentFeedbackRequest_Account)(nil),
		(*InitialiseAgentFeedbackRequest_Idea)(nil),
		(*InitialiseAgentFeedbackRequest_Token)(nil),
		(*InitialiseAgentFeedbackRequest_Note_)(nil),
		(*InitialiseAgentFeedbackRequest_AudioNote_)(nil),
		(*InitialiseAgentFeedbackRequest_MultiFileUpload_)(nil),
	}
	file_alis_ideate_ideate_proto_msgTypes[9].OneofWrappers = []any{
		(*InitialiseAgentFeedbackResponse_Note_)(nil),
		(*InitialiseAgentFeedbackResponse_AudioNote_)(nil),
		(*InitialiseAgentFeedbackResponse_MultiFileUpload_)(nil),
	}
	file_alis_ideate_ideate_proto_msgTypes[14].OneofWrappers = []any{
		(*InitialiseAgentFeedbackRequest_AgentInteraction_AgentCard)(nil),
		(*InitialiseAgentFeedbackRequest_AgentInteraction_AgentCardUri)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_ideate_ideate_proto_rawDesc), len(file_alis_ideate_ideate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alis_ideate_ideate_proto_goTypes,
		DependencyIndexes: file_alis_ideate_ideate_proto_depIdxs,
		EnumInfos:         file_alis_ideate_ideate_proto_enumTypes,
		MessageInfos:      file_alis_ideate_ideate_proto_msgTypes,
	}.Build()
	File_alis_ideate_ideate_proto = out.File
	file_alis_ideate_ideate_proto_goTypes = nil
	file_alis_ideate_ideate_proto_depIdxs = nil
}
