// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/ideate/idea.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-02-17 11:56:01 UTC

package ideate

const ()
