// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/ideate/ideate.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-02-25 11:54:07 UTC

package ideate

const (
	// IdeateService_AddNote_FullMethodDescription returns the description of the alis.ideate.IdeateService.AddNote method.
	IdeateService_AddNote_FullMethodDescription = "Adds a new Idea with a note Stream type"
	// IdeateService_AddAudioNote_FullMethodDescription returns the description of the alis.ideate.IdeateService.AddAudioNote method.
	IdeateService_AddAudioNote_FullMethodDescription = "Adds a new Idea with a audio note Stream type"
	// IdeateService_AddMultiFileUpload_FullMethodDescription returns the description of the alis.ideate.IdeateService.AddMultiFileUpload method.
	IdeateService_AddMultiFileUpload_FullMethodDescription = "Adds a new Idea with a multi-file upload Stream type"
	// IdeateService_AddAgent_FullMethodDescription returns the description of the alis.ideate.IdeateService.AddAgent method.
	IdeateService_AddAgent_FullMethodDescription = "Adds a new Idea with a multi-file upload Stream type"
	// IdeateService_InitialiseAgentFeedback_FullMethodDescription returns the description of the alis.ideate.IdeateService.InitialiseAgentFeedback method.
	IdeateService_InitialiseAgentFeedback_FullMethodDescription = "Provides an easy to use entry point to provide feedback about the interaction with an agent This will essentially create a new Contribution Session within the StreamTarget\n with two Streams:\n 1. Agent type Stream - provides context to Ideate about the agent\n 2. {Whatever the Stream added stream was}\n\n The response contains both of the resulting Streams"
	// IdeateService_GetIdea_FullMethodDescription returns the description of the alis.ideate.IdeateService.GetIdea method.
	IdeateService_GetIdea_FullMethodDescription = "Gets an Idea by it's name"
	// IdeateService_GetStream_FullMethodDescription returns the description of the alis.ideate.IdeateService.GetStream method.
	IdeateService_GetStream_FullMethodDescription = "Gets a Stream by it's name"
	// IdeateService_GetSpec_FullMethodDescription returns the description of the alis.ideate.IdeateService.GetSpec method.
	IdeateService_GetSpec_FullMethodDescription = "Gets a Spec by it's name"
	// IdeateService_RetrieveIdeaSpecs_FullMethodDescription returns the description of the alis.ideate.IdeateService.RetrieveIdeaSpecs method.
	IdeateService_RetrieveIdeaSpecs_FullMethodDescription = "Retrieves the set of Specs associated with a specified Idea.\n If a Spec type is set, only Specs of that type will be returned.\n Otherwise, all generated Specs for the idea will be returned."
	// IdeateService_GenerateCustomAgentSpec_FullMethodDescription returns the description of the alis.ideate.IdeateService.GenerateCustomAgentSpec method.
	IdeateService_GenerateCustomAgentSpec_FullMethodDescription = "Generates a Custom Agent spec.\n This will generate a new spec from an idea, or regenerate an existing spec."
	// IdeateService_GenerateAgentFeedbackSpec_FullMethodDescription returns the description of the alis.ideate.IdeateService.GenerateAgentFeedbackSpec method.
	IdeateService_GenerateAgentFeedbackSpec_FullMethodDescription = "Generates an Agent Feedback spec.\n This will generate a new spec from an idea, or regenerate an existing spec."
	// IdeateService_TestIdeateAccess_FullMethodDescription returns the description of the alis.ideate.IdeateService.TestIdeateAccess method.
	IdeateService_TestIdeateAccess_FullMethodDescription = "Tests whether the caller has access to Ideate for a specific account"
	// IdeateService_GetOperation_FullMethodDescription returns the description of the alis.ideate.IdeateService.GetOperation method.
	IdeateService_GetOperation_FullMethodDescription = "Returns the given lro"
)
