// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/ideate/spec.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-05-12 12:21:19 UTC

package ideate

const ()
