// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/ideate/spec.proto

package ideate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of the Spec
type Spec_Type int32

const (
	// Unspecified type
	Spec_TYPE_UNSPECIFIED Spec_Type = 0
	// Full Request for Proposal (RFP)
	Spec_FULL_RFP Spec_Type = 1
	// A brief document for an Idea, outlining the core concept,
	// description of the Idea, overview of the context and a
	// description of the potential outstanding areas.
	Spec_IDEA_BRIEF Spec_Type = 5
	// A UI prompt Spec that can be provided to Product
	// such as Stitch to generate a UI mock up from.
	Spec_UI_DESIGN Spec_Type = 6
	// A Spec that can be provided as input for a prototyping
	// tool such as Lovable to create the overall functionality.
	Spec_AI_PROTOTYPE Spec_Type = 7
	// Our opinionated attempt at what a good general specification looks like
	Spec_IDEATE_SPEC Spec_Type = 8
	// A business case output
	Spec_BUSINESS_CASE Spec_Type = 9
	// A prompt Spec that can be provided to Product
	// such as Lucid Charts to generate a Solution Flow diagram.
	Spec_SOLUTION_FLOW_SPEC Spec_Type = 10
	// A spec that is crafted by the user.
	Spec_CRAFTED_SPEC Spec_Type = 11
	// A clear articulation of the various current/as-is processes.
	Spec_CURRENT_PROCESS Spec_Type = 12
	// A list of jargon terms and definitions used across the idea
	Spec_JARGON Spec_Type = 13
	// An overview of the technology landscape.
	Spec_TECHNOLOGY_LANDSCAPE Spec_Type = 14
	// A list of pain points identified across different contributions
	Spec_PAIN_POINTS Spec_Type = 15
	// A mapping of the stakeholders identified across different contributions
	Spec_STAKEHOLDER_MAP Spec_Type = 16
	// A Figma Make spec.
	Spec_FIGMA_MAKE Spec_Type = 17
	// A Gemini Enterprise Custom Agent spec.
	Spec_GEMINI_ENTERPRISE_CUSTOM_AGENT Spec_Type = 18
	// An AI Studio Spec
	Spec_AI_STUDIO Spec_Type = 19
	// A Research Plan spec
	Spec_RESEARCH_PLAN Spec_Type = 20
	// A Custom Agent spec.
	Spec_CUSTOM_AGENT Spec_Type = 21
	// A product requirements document spec.
	Spec_PRODUCT_REQUIREMENTS_DOCUMENT Spec_Type = 22
	// An agent feedback spec.
	Spec_AGENT_FEEDBACK Spec_Type = 23
)

// Enum value maps for Spec_Type.
var (
	Spec_Type_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		1:  "FULL_RFP",
		5:  "IDEA_BRIEF",
		6:  "UI_DESIGN",
		7:  "AI_PROTOTYPE",
		8:  "IDEATE_SPEC",
		9:  "BUSINESS_CASE",
		10: "SOLUTION_FLOW_SPEC",
		11: "CRAFTED_SPEC",
		12: "CURRENT_PROCESS",
		13: "JARGON",
		14: "TECHNOLOGY_LANDSCAPE",
		15: "PAIN_POINTS",
		16: "STAKEHOLDER_MAP",
		17: "FIGMA_MAKE",
		18: "GEMINI_ENTERPRISE_CUSTOM_AGENT",
		19: "AI_STUDIO",
		20: "RESEARCH_PLAN",
		21: "CUSTOM_AGENT",
		22: "PRODUCT_REQUIREMENTS_DOCUMENT",
		23: "AGENT_FEEDBACK",
	}
	Spec_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":               0,
		"FULL_RFP":                       1,
		"IDEA_BRIEF":                     5,
		"UI_DESIGN":                      6,
		"AI_PROTOTYPE":                   7,
		"IDEATE_SPEC":                    8,
		"BUSINESS_CASE":                  9,
		"SOLUTION_FLOW_SPEC":             10,
		"CRAFTED_SPEC":                   11,
		"CURRENT_PROCESS":                12,
		"JARGON":                         13,
		"TECHNOLOGY_LANDSCAPE":           14,
		"PAIN_POINTS":                    15,
		"STAKEHOLDER_MAP":                16,
		"FIGMA_MAKE":                     17,
		"GEMINI_ENTERPRISE_CUSTOM_AGENT": 18,
		"AI_STUDIO":                      19,
		"RESEARCH_PLAN":                  20,
		"CUSTOM_AGENT":                   21,
		"PRODUCT_REQUIREMENTS_DOCUMENT":  22,
		"AGENT_FEEDBACK":                 23,
	}
)

func (x Spec_Type) Enum() *Spec_Type {
	p := new(Spec_Type)
	*p = x
	return p
}

func (x Spec_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Spec_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_ideate_spec_proto_enumTypes[0].Descriptor()
}

func (Spec_Type) Type() protoreflect.EnumType {
	return &file_alis_ideate_spec_proto_enumTypes[0]
}

func (x Spec_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Spec_Type.Descriptor instead.
func (Spec_Type) EnumDescriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 0}
}

// Potential states
type Spec_State int32

const (
	// State is unspecified
	Spec_STATE_UNSPECIFIED Spec_State = 0
	// The Spec is in a draft state, this is the default state when a
	// new Spec is created.
	Spec_DRAFT Spec_State = 1
	// The the Spec has been published and can no longer be edited
	// TODO: revisit this?
	Spec_PUBLISHED Spec_State = 2
	// The the Spec has been archived
	Spec_ARCHIVED Spec_State = 3
	// The GenAI is actively processing the Spec. This is the
	// state where the core generate logic is executed.
	Spec_PROCESSING Spec_State = 4
	// The GenAI processing has completed successfully and the Spec has been
	// enriched. This is a key success state.
	Spec_READY Spec_State = 5
	// Failed to parse the content of the Stream
	Spec_FAILED Spec_State = 6
	// The Spec is stale - ie. the Idea contains contributions
	// that is not yet reflected in the Spec
	Spec_STALE Spec_State = 7
)

// Enum value maps for Spec_State.
var (
	Spec_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "DRAFT",
		2: "PUBLISHED",
		3: "ARCHIVED",
		4: "PROCESSING",
		5: "READY",
		6: "FAILED",
		7: "STALE",
	}
	Spec_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"DRAFT":             1,
		"PUBLISHED":         2,
		"ARCHIVED":          3,
		"PROCESSING":        4,
		"READY":             5,
		"FAILED":            6,
		"STALE":             7,
	}
)

func (x Spec_State) Enum() *Spec_State {
	p := new(Spec_State)
	*p = x
	return p
}

func (x Spec_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Spec_State) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_ideate_spec_proto_enumTypes[1].Descriptor()
}

func (Spec_State) Type() protoreflect.EnumType {
	return &file_alis_ideate_spec_proto_enumTypes[1]
}

func (x Spec_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Spec_State.Descriptor instead.
func (Spec_State) EnumDescriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 1}
}

// A Spec resource provides the overall synthesis of an Idea
// into a structured and clear specification. The content
// of the Spec is determined by the type of Spec generated.
type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the Spec.
	// Format: specs/*
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The title of the the Spec
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The type of the the Spec
	Type Spec_Type `protobuf:"varint,3,opt,name=type,proto3,enum=alis.ideate.Spec_Type" json:"type,omitempty"`
	// The Idea associated with the the Spec
	// Format: ideas/*
	Idea string `protobuf:"bytes,4,opt,name=idea,proto3" json:"idea,omitempty"`
	// The state of the the Spec
	State Spec_State `protobuf:"varint,5,opt,name=state,proto3,enum=alis.ideate.Spec_State" json:"state,omitempty"`
	// The output of the Spec, which is determined by the type of Spec.
	//
	// Types that are valid to be assigned to Output:
	//
	//	*Spec_FullRfp_
	//	*Spec_IdeaBrief_
	//	*Spec_UiDesign_
	//	*Spec_AiPrototype_
	//	*Spec_IdeateSpec_
	//	*Spec_BusinessCase_
	//	*Spec_CurrentProcess_
	//	*Spec_Jargon_
	//	*Spec_TechnologyLandscape_
	//	*Spec_PainPoints_
	//	*Spec_StakeholderMap_
	//	*Spec_FigmaMake_
	//	*Spec_GeminiEnterpriseCustomAgent
	//	*Spec_AiStudio_
	//	*Spec_SolutionFlowSpec_
	//	*Spec_ResearchPlan_
	//	*Spec_CustomAgent_
	//	*Spec_ProductRequirementsDocument_
	//	*Spec_AgentFeedback_
	Output isSpec_Output `protobuf_oneof:"output"`
	// Context used to generate this Spec.
	GenerationContext *Spec_GenerationContext `protobuf:"bytes,95,opt,name=generation_context,json=generationContext,proto3" json:"generation_context,omitempty"`
	// The LRO associated with the the Spec
	// Format: operations/*
	Operation string `protobuf:"bytes,96,opt,name=operation,proto3" json:"operation,omitempty"`
	// When this spec was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When this spec was updated.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// When this spec was deleted, if applicable.
	DeleteTime    *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=delete_time,json=deleteTime,proto3" json:"delete_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_alis_ideate_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0}
}

func (x *Spec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Spec) GetType() Spec_Type {
	if x != nil {
		return x.Type
	}
	return Spec_TYPE_UNSPECIFIED
}

func (x *Spec) GetIdea() string {
	if x != nil {
		return x.Idea
	}
	return ""
}

func (x *Spec) GetState() Spec_State {
	if x != nil {
		return x.State
	}
	return Spec_STATE_UNSPECIFIED
}

func (x *Spec) GetOutput() isSpec_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Spec) GetFullRfp() *Spec_FullRfp {
	if x != nil {
		if x, ok := x.Output.(*Spec_FullRfp_); ok {
			return x.FullRfp
		}
	}
	return nil
}

func (x *Spec) GetIdeaBrief() *Spec_IdeaBrief {
	if x != nil {
		if x, ok := x.Output.(*Spec_IdeaBrief_); ok {
			return x.IdeaBrief
		}
	}
	return nil
}

func (x *Spec) GetUiDesign() *Spec_UiDesign {
	if x != nil {
		if x, ok := x.Output.(*Spec_UiDesign_); ok {
			return x.UiDesign
		}
	}
	return nil
}

func (x *Spec) GetAiPrototype() *Spec_AiPrototype {
	if x != nil {
		if x, ok := x.Output.(*Spec_AiPrototype_); ok {
			return x.AiPrototype
		}
	}
	return nil
}

func (x *Spec) GetIdeateSpec() *Spec_IdeateSpec {
	if x != nil {
		if x, ok := x.Output.(*Spec_IdeateSpec_); ok {
			return x.IdeateSpec
		}
	}
	return nil
}

func (x *Spec) GetBusinessCase() *Spec_BusinessCase {
	if x != nil {
		if x, ok := x.Output.(*Spec_BusinessCase_); ok {
			return x.BusinessCase
		}
	}
	return nil
}

func (x *Spec) GetCurrentProcess() *Spec_CurrentProcess {
	if x != nil {
		if x, ok := x.Output.(*Spec_CurrentProcess_); ok {
			return x.CurrentProcess
		}
	}
	return nil
}

func (x *Spec) GetJargon() *Spec_Jargon {
	if x != nil {
		if x, ok := x.Output.(*Spec_Jargon_); ok {
			return x.Jargon
		}
	}
	return nil
}

func (x *Spec) GetTechnologyLandscape() *Spec_TechnologyLandscape {
	if x != nil {
		if x, ok := x.Output.(*Spec_TechnologyLandscape_); ok {
			return x.TechnologyLandscape
		}
	}
	return nil
}

func (x *Spec) GetPainPoints() *Spec_PainPoints {
	if x != nil {
		if x, ok := x.Output.(*Spec_PainPoints_); ok {
			return x.PainPoints
		}
	}
	return nil
}

func (x *Spec) GetStakeholderMap() *Spec_StakeholderMap {
	if x != nil {
		if x, ok := x.Output.(*Spec_StakeholderMap_); ok {
			return x.StakeholderMap
		}
	}
	return nil
}

func (x *Spec) GetFigmaMake() *Spec_FigmaMake {
	if x != nil {
		if x, ok := x.Output.(*Spec_FigmaMake_); ok {
			return x.FigmaMake
		}
	}
	return nil
}

func (x *Spec) GetGeminiEnterpriseCustomAgent() *Spec_GeminiEnterpriseCustomAgentSpec {
	if x != nil {
		if x, ok := x.Output.(*Spec_GeminiEnterpriseCustomAgent); ok {
			return x.GeminiEnterpriseCustomAgent
		}
	}
	return nil
}

func (x *Spec) GetAiStudio() *Spec_AiStudio {
	if x != nil {
		if x, ok := x.Output.(*Spec_AiStudio_); ok {
			return x.AiStudio
		}
	}
	return nil
}

func (x *Spec) GetSolutionFlowSpec() *Spec_SolutionFlowSpec {
	if x != nil {
		if x, ok := x.Output.(*Spec_SolutionFlowSpec_); ok {
			return x.SolutionFlowSpec
		}
	}
	return nil
}

func (x *Spec) GetResearchPlan() *Spec_ResearchPlan {
	if x != nil {
		if x, ok := x.Output.(*Spec_ResearchPlan_); ok {
			return x.ResearchPlan
		}
	}
	return nil
}

func (x *Spec) GetCustomAgent() *Spec_CustomAgent {
	if x != nil {
		if x, ok := x.Output.(*Spec_CustomAgent_); ok {
			return x.CustomAgent
		}
	}
	return nil
}

func (x *Spec) GetProductRequirementsDocument() *Spec_ProductRequirementsDocument {
	if x != nil {
		if x, ok := x.Output.(*Spec_ProductRequirementsDocument_); ok {
			return x.ProductRequirementsDocument
		}
	}
	return nil
}

func (x *Spec) GetAgentFeedback() *Spec_AgentFeedback {
	if x != nil {
		if x, ok := x.Output.(*Spec_AgentFeedback_); ok {
			return x.AgentFeedback
		}
	}
	return nil
}

func (x *Spec) GetGenerationContext() *Spec_GenerationContext {
	if x != nil {
		return x.GenerationContext
	}
	return nil
}

func (x *Spec) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Spec) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Spec) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Spec) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

type isSpec_Output interface {
	isSpec_Output()
}

type Spec_FullRfp_ struct {
	// A full Request for Proposal (RFP).
	FullRfp *Spec_FullRfp `protobuf:"bytes,6,opt,name=full_rfp,json=fullRfp,proto3,oneof"`
}

type Spec_IdeaBrief_ struct {
	// A brief for an idea.
	IdeaBrief *Spec_IdeaBrief `protobuf:"bytes,7,opt,name=idea_brief,json=ideaBrief,proto3,oneof"`
}

type Spec_UiDesign_ struct {
	// A UI design spec.
	UiDesign *Spec_UiDesign `protobuf:"bytes,8,opt,name=ui_design,json=uiDesign,proto3,oneof"`
}

type Spec_AiPrototype_ struct {
	// An AI prototype spec.
	AiPrototype *Spec_AiPrototype `protobuf:"bytes,9,opt,name=ai_prototype,json=aiPrototype,proto3,oneof"`
}

type Spec_IdeateSpec_ struct {
	// An Ideate spec.
	IdeateSpec *Spec_IdeateSpec `protobuf:"bytes,10,opt,name=ideate_spec,json=ideateSpec,proto3,oneof"`
}

type Spec_BusinessCase_ struct {
	// A business case.
	BusinessCase *Spec_BusinessCase `protobuf:"bytes,11,opt,name=business_case,json=businessCase,proto3,oneof"`
}

type Spec_CurrentProcess_ struct {
	// A description of the current process.
	CurrentProcess *Spec_CurrentProcess `protobuf:"bytes,12,opt,name=current_process,json=currentProcess,proto3,oneof"`
}

type Spec_Jargon_ struct {
	// A list of jargon terms and definitions.
	Jargon *Spec_Jargon `protobuf:"bytes,13,opt,name=jargon,proto3,oneof"`
}

type Spec_TechnologyLandscape_ struct {
	// An overview of the technology landscape.
	TechnologyLandscape *Spec_TechnologyLandscape `protobuf:"bytes,14,opt,name=technology_landscape,json=technologyLandscape,proto3,oneof"`
}

type Spec_PainPoints_ struct {
	// A list of pain points.
	PainPoints *Spec_PainPoints `protobuf:"bytes,15,opt,name=pain_points,json=painPoints,proto3,oneof"`
}

type Spec_StakeholderMap_ struct {
	// A map of stakeholders.
	StakeholderMap *Spec_StakeholderMap `protobuf:"bytes,16,opt,name=stakeholder_map,json=stakeholderMap,proto3,oneof"`
}

type Spec_FigmaMake_ struct {
	// A Figma Make spec.
	FigmaMake *Spec_FigmaMake `protobuf:"bytes,17,opt,name=figma_make,json=figmaMake,proto3,oneof"`
}

type Spec_GeminiEnterpriseCustomAgent struct {
	// A Gemini Enterprise Custom Agent spec.
	GeminiEnterpriseCustomAgent *Spec_GeminiEnterpriseCustomAgentSpec `protobuf:"bytes,18,opt,name=gemini_enterprise_custom_agent,json=geminiEnterpriseCustomAgent,proto3,oneof"`
}

type Spec_AiStudio_ struct {
	// An AI Studio Spec
	AiStudio *Spec_AiStudio `protobuf:"bytes,19,opt,name=ai_studio,json=aiStudio,proto3,oneof"`
}

type Spec_SolutionFlowSpec_ struct {
	// A Solution Flow spec
	SolutionFlowSpec *Spec_SolutionFlowSpec `protobuf:"bytes,20,opt,name=solution_flow_spec,json=solutionFlowSpec,proto3,oneof"`
}

type Spec_ResearchPlan_ struct {
	// A research plan.
	ResearchPlan *Spec_ResearchPlan `protobuf:"bytes,21,opt,name=research_plan,json=researchPlan,proto3,oneof"`
}

type Spec_CustomAgent_ struct {
	// A custom agent.
	CustomAgent *Spec_CustomAgent `protobuf:"bytes,22,opt,name=custom_agent,json=customAgent,proto3,oneof"`
}

type Spec_ProductRequirementsDocument_ struct {
	// A product requirements document.
	ProductRequirementsDocument *Spec_ProductRequirementsDocument `protobuf:"bytes,23,opt,name=product_requirements_document,json=productRequirementsDocument,proto3,oneof"`
}

type Spec_AgentFeedback_ struct {
	// An agent feedback.
	AgentFeedback *Spec_AgentFeedback `protobuf:"bytes,24,opt,name=agent_feedback,json=agentFeedback,proto3,oneof"`
}

func (*Spec_FullRfp_) isSpec_Output() {}

func (*Spec_IdeaBrief_) isSpec_Output() {}

func (*Spec_UiDesign_) isSpec_Output() {}

func (*Spec_AiPrototype_) isSpec_Output() {}

func (*Spec_IdeateSpec_) isSpec_Output() {}

func (*Spec_BusinessCase_) isSpec_Output() {}

func (*Spec_CurrentProcess_) isSpec_Output() {}

func (*Spec_Jargon_) isSpec_Output() {}

func (*Spec_TechnologyLandscape_) isSpec_Output() {}

func (*Spec_PainPoints_) isSpec_Output() {}

func (*Spec_StakeholderMap_) isSpec_Output() {}

func (*Spec_FigmaMake_) isSpec_Output() {}

func (*Spec_GeminiEnterpriseCustomAgent) isSpec_Output() {}

func (*Spec_AiStudio_) isSpec_Output() {}

func (*Spec_SolutionFlowSpec_) isSpec_Output() {}

func (*Spec_ResearchPlan_) isSpec_Output() {}

func (*Spec_CustomAgent_) isSpec_Output() {}

func (*Spec_ProductRequirementsDocument_) isSpec_Output() {}

func (*Spec_AgentFeedback_) isSpec_Output() {}

// Request to get an spec.
type GetSpecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the Spec to retrieve.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A read mask to specify which fields to return.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpecRequest) Reset() {
	*x = GetSpecRequest{}
	mi := &file_alis_ideate_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecRequest) ProtoMessage() {}

func (x *GetSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecRequest.ProtoReflect.Descriptor instead.
func (*GetSpecRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{1}
}

func (x *GetSpecRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSpecRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Request to generate a Custom Agent spec.
type GenerateCustomAgentSpecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source for generating the spec.
	//
	// Types that are valid to be assigned to Source:
	//
	//	*GenerateCustomAgentSpecRequest_Idea
	//	*GenerateCustomAgentSpecRequest_Spec
	Source isGenerateCustomAgentSpecRequest_Source `protobuf_oneof:"source"`
	// Context used to generate this Spec.
	GenerationContext *Spec_GenerationContext `protobuf:"bytes,3,opt,name=generation_context,json=generationContext,proto3" json:"generation_context,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateCustomAgentSpecRequest) Reset() {
	*x = GenerateCustomAgentSpecRequest{}
	mi := &file_alis_ideate_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCustomAgentSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCustomAgentSpecRequest) ProtoMessage() {}

func (x *GenerateCustomAgentSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCustomAgentSpecRequest.ProtoReflect.Descriptor instead.
func (*GenerateCustomAgentSpecRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateCustomAgentSpecRequest) GetSource() isGenerateCustomAgentSpecRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *GenerateCustomAgentSpecRequest) GetIdea() string {
	if x != nil {
		if x, ok := x.Source.(*GenerateCustomAgentSpecRequest_Idea); ok {
			return x.Idea
		}
	}
	return ""
}

func (x *GenerateCustomAgentSpecRequest) GetSpec() string {
	if x != nil {
		if x, ok := x.Source.(*GenerateCustomAgentSpecRequest_Spec); ok {
			return x.Spec
		}
	}
	return ""
}

func (x *GenerateCustomAgentSpecRequest) GetGenerationContext() *Spec_GenerationContext {
	if x != nil {
		return x.GenerationContext
	}
	return nil
}

type isGenerateCustomAgentSpecRequest_Source interface {
	isGenerateCustomAgentSpecRequest_Source()
}

type GenerateCustomAgentSpecRequest_Idea struct {
	// The idea to generate the spec from.
	// Format: ideas/{idea_id}
	Idea string `protobuf:"bytes,1,opt,name=idea,proto3,oneof"`
}

type GenerateCustomAgentSpecRequest_Spec struct {
	// The existing spec to regenerate.
	// Format: specs/{spec_id}
	Spec string `protobuf:"bytes,2,opt,name=spec,proto3,oneof"`
}

func (*GenerateCustomAgentSpecRequest_Idea) isGenerateCustomAgentSpecRequest_Source() {}

func (*GenerateCustomAgentSpecRequest_Spec) isGenerateCustomAgentSpecRequest_Source() {}

// Data required for long running portion of the GenerateCustomAgentSpec RPC method
// to continue running
type GenerateCustomAgentSpecMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request message for the GenerateCustomAgentSpec rpc
	GenerateCustomAgentSpecRequest *GenerateCustomAgentSpecRequest `protobuf:"bytes,1,opt,name=generate_custom_agent_spec_request,json=generateCustomAgentSpecRequest,proto3" json:"generate_custom_agent_spec_request,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GenerateCustomAgentSpecMetadata) Reset() {
	*x = GenerateCustomAgentSpecMetadata{}
	mi := &file_alis_ideate_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCustomAgentSpecMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCustomAgentSpecMetadata) ProtoMessage() {}

func (x *GenerateCustomAgentSpecMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCustomAgentSpecMetadata.ProtoReflect.Descriptor instead.
func (*GenerateCustomAgentSpecMetadata) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateCustomAgentSpecMetadata) GetGenerateCustomAgentSpecRequest() *GenerateCustomAgentSpecRequest {
	if x != nil {
		return x.GenerateCustomAgentSpecRequest
	}
	return nil
}

// Response for generating a Custom Agent spec.
type GenerateCustomAgentSpecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generated Spec
	Spec          *Spec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCustomAgentSpecResponse) Reset() {
	*x = GenerateCustomAgentSpecResponse{}
	mi := &file_alis_ideate_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCustomAgentSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCustomAgentSpecResponse) ProtoMessage() {}

func (x *GenerateCustomAgentSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCustomAgentSpecResponse.ProtoReflect.Descriptor instead.
func (*GenerateCustomAgentSpecResponse) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateCustomAgentSpecResponse) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Request to retrieve Specs for a specified idea
type RetrieveIdeaSpecsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Idea for which to retrieve Specs
	// ideas/*
	Idea string `protobuf:"bytes,1,opt,name=idea,proto3" json:"idea,omitempty"`
	// The type of Spec to retrieve.
	// If unspecified, will retrieve all existing Specs.
	SpecType      Spec_Type `protobuf:"varint,2,opt,name=spec_type,json=specType,proto3,enum=alis.ideate.Spec_Type" json:"spec_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveIdeaSpecsRequest) Reset() {
	*x = RetrieveIdeaSpecsRequest{}
	mi := &file_alis_ideate_spec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveIdeaSpecsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveIdeaSpecsRequest) ProtoMessage() {}

func (x *RetrieveIdeaSpecsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveIdeaSpecsRequest.ProtoReflect.Descriptor instead.
func (*RetrieveIdeaSpecsRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{5}
}

func (x *RetrieveIdeaSpecsRequest) GetIdea() string {
	if x != nil {
		return x.Idea
	}
	return ""
}

func (x *RetrieveIdeaSpecsRequest) GetSpecType() Spec_Type {
	if x != nil {
		return x.SpecType
	}
	return Spec_TYPE_UNSPECIFIED
}

// Response to generate a section of an Spec
type RetrieveIdeaSpecsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The set of Specs associated with the Specified Idea.
	Specs         []*Spec `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveIdeaSpecsResponse) Reset() {
	*x = RetrieveIdeaSpecsResponse{}
	mi := &file_alis_ideate_spec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveIdeaSpecsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveIdeaSpecsResponse) ProtoMessage() {}

func (x *RetrieveIdeaSpecsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveIdeaSpecsResponse.ProtoReflect.Descriptor instead.
func (*RetrieveIdeaSpecsResponse) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{6}
}

func (x *RetrieveIdeaSpecsResponse) GetSpecs() []*Spec {
	if x != nil {
		return x.Specs
	}
	return nil
}

// Request to generate an Agent Feedback spec.
type GenerateAgentFeedbackSpecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source for generating the spec.
	//
	// Types that are valid to be assigned to Source:
	//
	//	*GenerateAgentFeedbackSpecRequest_Idea
	//	*GenerateAgentFeedbackSpecRequest_Spec
	Source isGenerateAgentFeedbackSpecRequest_Source `protobuf_oneof:"source"`
	// Context used to generate this Spec.
	GenerationContext *Spec_GenerationContext `protobuf:"bytes,3,opt,name=generation_context,json=generationContext,proto3" json:"generation_context,omitempty"`
	// The names of the streams that point to the agent stream under feedback
	// Format: ideas/*/streams/*
	//
	// If NOT specified, will generate feedback for all agent streams in the idea.
	TargetAgents  []string `protobuf:"bytes,4,rep,name=target_agents,json=targetAgents,proto3" json:"target_agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAgentFeedbackSpecRequest) Reset() {
	*x = GenerateAgentFeedbackSpecRequest{}
	mi := &file_alis_ideate_spec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAgentFeedbackSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAgentFeedbackSpecRequest) ProtoMessage() {}

func (x *GenerateAgentFeedbackSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAgentFeedbackSpecRequest.ProtoReflect.Descriptor instead.
func (*GenerateAgentFeedbackSpecRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateAgentFeedbackSpecRequest) GetSource() isGenerateAgentFeedbackSpecRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *GenerateAgentFeedbackSpecRequest) GetIdea() string {
	if x != nil {
		if x, ok := x.Source.(*GenerateAgentFeedbackSpecRequest_Idea); ok {
			return x.Idea
		}
	}
	return ""
}

func (x *GenerateAgentFeedbackSpecRequest) GetSpec() string {
	if x != nil {
		if x, ok := x.Source.(*GenerateAgentFeedbackSpecRequest_Spec); ok {
			return x.Spec
		}
	}
	return ""
}

func (x *GenerateAgentFeedbackSpecRequest) GetGenerationContext() *Spec_GenerationContext {
	if x != nil {
		return x.GenerationContext
	}
	return nil
}

func (x *GenerateAgentFeedbackSpecRequest) GetTargetAgents() []string {
	if x != nil {
		return x.TargetAgents
	}
	return nil
}

type isGenerateAgentFeedbackSpecRequest_Source interface {
	isGenerateAgentFeedbackSpecRequest_Source()
}

type GenerateAgentFeedbackSpecRequest_Idea struct {
	// The idea to generate the spec from.
	// Format: ideas/{idea_id}
	Idea string `protobuf:"bytes,1,opt,name=idea,proto3,oneof"`
}

type GenerateAgentFeedbackSpecRequest_Spec struct {
	// The existing spec to regenerate.
	// Format: specs/{spec_id}
	Spec string `protobuf:"bytes,2,opt,name=spec,proto3,oneof"`
}

func (*GenerateAgentFeedbackSpecRequest_Idea) isGenerateAgentFeedbackSpecRequest_Source() {}

func (*GenerateAgentFeedbackSpecRequest_Spec) isGenerateAgentFeedbackSpecRequest_Source() {}

// Data required for long running portion of the GenerateAgentFeedbackSpec RPC method
// to continue running
type GenerateAgentFeedbackSpecMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request message for the GenerateAgentFeedbackSpec rpc
	GenerateAgentFeedbackSpecRequest *GenerateAgentFeedbackSpecRequest `protobuf:"bytes,1,opt,name=generate_agent_feedback_spec_request,json=generateAgentFeedbackSpecRequest,proto3" json:"generate_agent_feedback_spec_request,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *GenerateAgentFeedbackSpecMetadata) Reset() {
	*x = GenerateAgentFeedbackSpecMetadata{}
	mi := &file_alis_ideate_spec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAgentFeedbackSpecMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAgentFeedbackSpecMetadata) ProtoMessage() {}

func (x *GenerateAgentFeedbackSpecMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAgentFeedbackSpecMetadata.ProtoReflect.Descriptor instead.
func (*GenerateAgentFeedbackSpecMetadata) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateAgentFeedbackSpecMetadata) GetGenerateAgentFeedbackSpecRequest() *GenerateAgentFeedbackSpecRequest {
	if x != nil {
		return x.GenerateAgentFeedbackSpecRequest
	}
	return nil
}

// Response for generating an Agent Feedback spec.
type GenerateAgentFeedbackSpecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generated Spec
	Spec          *Spec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAgentFeedbackSpecResponse) Reset() {
	*x = GenerateAgentFeedbackSpecResponse{}
	mi := &file_alis_ideate_spec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAgentFeedbackSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAgentFeedbackSpecResponse) ProtoMessage() {}

func (x *GenerateAgentFeedbackSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAgentFeedbackSpecResponse.ProtoReflect.Descriptor instead.
func (*GenerateAgentFeedbackSpecResponse) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateAgentFeedbackSpecResponse) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// A full Request for Proposal (RFP).
type Spec_FullRfp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the RFP.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_FullRfp) Reset() {
	*x = Spec_FullRfp{}
	mi := &file_alis_ideate_spec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_FullRfp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_FullRfp) ProtoMessage() {}

func (x *Spec_FullRfp) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_FullRfp.ProtoReflect.Descriptor instead.
func (*Spec_FullRfp) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Spec_FullRfp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A brief for an idea.
type Spec_IdeaBrief struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the brief.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_IdeaBrief) Reset() {
	*x = Spec_IdeaBrief{}
	mi := &file_alis_ideate_spec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_IdeaBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_IdeaBrief) ProtoMessage() {}

func (x *Spec_IdeaBrief) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_IdeaBrief.ProtoReflect.Descriptor instead.
func (*Spec_IdeaBrief) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Spec_IdeaBrief) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A UI design spec.
type Spec_UiDesign struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the UI design.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_UiDesign) Reset() {
	*x = Spec_UiDesign{}
	mi := &file_alis_ideate_spec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_UiDesign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_UiDesign) ProtoMessage() {}

func (x *Spec_UiDesign) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_UiDesign.ProtoReflect.Descriptor instead.
func (*Spec_UiDesign) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Spec_UiDesign) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// An AI prototype spec.
type Spec_AiPrototype struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the AI prototype.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_AiPrototype) Reset() {
	*x = Spec_AiPrototype{}
	mi := &file_alis_ideate_spec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_AiPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_AiPrototype) ProtoMessage() {}

func (x *Spec_AiPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_AiPrototype.ProtoReflect.Descriptor instead.
func (*Spec_AiPrototype) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Spec_AiPrototype) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// An Ideate spec.
type Spec_IdeateSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the Ideate spec.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_IdeateSpec) Reset() {
	*x = Spec_IdeateSpec{}
	mi := &file_alis_ideate_spec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_IdeateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_IdeateSpec) ProtoMessage() {}

func (x *Spec_IdeateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_IdeateSpec.ProtoReflect.Descriptor instead.
func (*Spec_IdeateSpec) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Spec_IdeateSpec) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A business case.
type Spec_BusinessCase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the business case.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_BusinessCase) Reset() {
	*x = Spec_BusinessCase{}
	mi := &file_alis_ideate_spec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_BusinessCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_BusinessCase) ProtoMessage() {}

func (x *Spec_BusinessCase) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_BusinessCase.ProtoReflect.Descriptor instead.
func (*Spec_BusinessCase) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Spec_BusinessCase) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Solution flow chart spec.
type Spec_SolutionFlowSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the business case.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_SolutionFlowSpec) Reset() {
	*x = Spec_SolutionFlowSpec{}
	mi := &file_alis_ideate_spec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_SolutionFlowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_SolutionFlowSpec) ProtoMessage() {}

func (x *Spec_SolutionFlowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_SolutionFlowSpec.ProtoReflect.Descriptor instead.
func (*Spec_SolutionFlowSpec) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Spec_SolutionFlowSpec) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A crafted spec.
type Spec_CraftedSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the crafted spec.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_CraftedSpec) Reset() {
	*x = Spec_CraftedSpec{}
	mi := &file_alis_ideate_spec_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_CraftedSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_CraftedSpec) ProtoMessage() {}

func (x *Spec_CraftedSpec) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_CraftedSpec.ProtoReflect.Descriptor instead.
func (*Spec_CraftedSpec) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Spec_CraftedSpec) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A description of the current process.
type Spec_CurrentProcess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_CurrentProcess) Reset() {
	*x = Spec_CurrentProcess{}
	mi := &file_alis_ideate_spec_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_CurrentProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_CurrentProcess) ProtoMessage() {}

func (x *Spec_CurrentProcess) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_CurrentProcess.ProtoReflect.Descriptor instead.
func (*Spec_CurrentProcess) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Spec_CurrentProcess) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A list of jargon terms and definitions.
type Spec_Jargon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_Jargon) Reset() {
	*x = Spec_Jargon{}
	mi := &file_alis_ideate_spec_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_Jargon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_Jargon) ProtoMessage() {}

func (x *Spec_Jargon) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_Jargon.ProtoReflect.Descriptor instead.
func (*Spec_Jargon) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Spec_Jargon) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// An overview of the technology landscape.
type Spec_TechnologyLandscape struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_TechnologyLandscape) Reset() {
	*x = Spec_TechnologyLandscape{}
	mi := &file_alis_ideate_spec_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_TechnologyLandscape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_TechnologyLandscape) ProtoMessage() {}

func (x *Spec_TechnologyLandscape) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_TechnologyLandscape.ProtoReflect.Descriptor instead.
func (*Spec_TechnologyLandscape) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Spec_TechnologyLandscape) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A list of pain points.
type Spec_PainPoints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_PainPoints) Reset() {
	*x = Spec_PainPoints{}
	mi := &file_alis_ideate_spec_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_PainPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_PainPoints) ProtoMessage() {}

func (x *Spec_PainPoints) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_PainPoints.ProtoReflect.Descriptor instead.
func (*Spec_PainPoints) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Spec_PainPoints) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A map of stakeholders.
type Spec_StakeholderMap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_StakeholderMap) Reset() {
	*x = Spec_StakeholderMap{}
	mi := &file_alis_ideate_spec_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_StakeholderMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_StakeholderMap) ProtoMessage() {}

func (x *Spec_StakeholderMap) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_StakeholderMap.ProtoReflect.Descriptor instead.
func (*Spec_StakeholderMap) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 12}
}

func (x *Spec_StakeholderMap) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A Figma Make spec.
type Spec_FigmaMake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content which serves as a declarative description of what
	// is required
	//
	// Content is the Terraform
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_FigmaMake) Reset() {
	*x = Spec_FigmaMake{}
	mi := &file_alis_ideate_spec_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_FigmaMake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_FigmaMake) ProtoMessage() {}

func (x *Spec_FigmaMake) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_FigmaMake.ProtoReflect.Descriptor instead.
func (*Spec_FigmaMake) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 13}
}

func (x *Spec_FigmaMake) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A Gemini Enterprise Custom Agent spec.
type Spec_GeminiEnterpriseCustomAgentSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The display name of the agent.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The description of the agent.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The instructions for the agent.
	Instructions  string `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_GeminiEnterpriseCustomAgentSpec) Reset() {
	*x = Spec_GeminiEnterpriseCustomAgentSpec{}
	mi := &file_alis_ideate_spec_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_GeminiEnterpriseCustomAgentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_GeminiEnterpriseCustomAgentSpec) ProtoMessage() {}

func (x *Spec_GeminiEnterpriseCustomAgentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_GeminiEnterpriseCustomAgentSpec.ProtoReflect.Descriptor instead.
func (*Spec_GeminiEnterpriseCustomAgentSpec) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 14}
}

func (x *Spec_GeminiEnterpriseCustomAgentSpec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Spec_GeminiEnterpriseCustomAgentSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spec_GeminiEnterpriseCustomAgentSpec) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type Spec_AiStudio struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content which serves as a declarative description of what
	// is required
	//
	// Content is the Terraform
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// The name of the Contribution Session, in the case that it was linked to
	// the Spec
	//
	// Format: contributionSessions/*
	ContributionSession string `protobuf:"bytes,2,opt,name=contribution_session,json=contributionSession,proto3" json:"contribution_session,omitempty"`
	// Signed urls for attachments that can be uploaded into the AI Studio make prompt.
	// Current use: images of ui designs
	AttachmentUris []string `protobuf:"bytes,3,rep,name=attachment_uris,json=attachmentUris,proto3" json:"attachment_uris,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Spec_AiStudio) Reset() {
	*x = Spec_AiStudio{}
	mi := &file_alis_ideate_spec_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_AiStudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_AiStudio) ProtoMessage() {}

func (x *Spec_AiStudio) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_AiStudio.ProtoReflect.Descriptor instead.
func (*Spec_AiStudio) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 15}
}

func (x *Spec_AiStudio) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Spec_AiStudio) GetContributionSession() string {
	if x != nil {
		return x.ContributionSession
	}
	return ""
}

func (x *Spec_AiStudio) GetAttachmentUris() []string {
	if x != nil {
		return x.AttachmentUris
	}
	return nil
}

// A research plan
type Spec_ResearchPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The framing of the research plan, also regarded as the goal/problem statement
	// and overarching objectives of the research plan.
	//
	// Should be sufficient to communicate what would make
	// the research plan successful.
	Framing string `protobuf:"bytes,1,opt,name=framing,proto3" json:"framing,omitempty"`
	// The specific set of questions that are to be answered by the
	// for the study to be successful
	ResearchQuestions []string `protobuf:"bytes,2,rep,name=research_questions,json=researchQuestions,proto3" json:"research_questions,omitempty"`
	// The question that should be used to start the research
	LeadingQuestion string `protobuf:"bytes,3,opt,name=leading_question,json=leadingQuestion,proto3" json:"leading_question,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Spec_ResearchPlan) Reset() {
	*x = Spec_ResearchPlan{}
	mi := &file_alis_ideate_spec_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_ResearchPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_ResearchPlan) ProtoMessage() {}

func (x *Spec_ResearchPlan) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_ResearchPlan.ProtoReflect.Descriptor instead.
func (*Spec_ResearchPlan) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 16}
}

func (x *Spec_ResearchPlan) GetFraming() string {
	if x != nil {
		return x.Framing
	}
	return ""
}

func (x *Spec_ResearchPlan) GetResearchQuestions() []string {
	if x != nil {
		return x.ResearchQuestions
	}
	return nil
}

func (x *Spec_ResearchPlan) GetLeadingQuestion() string {
	if x != nil {
		return x.LeadingQuestion
	}
	return ""
}

// A custom agent.
type Spec_CustomAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the custom agent.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_CustomAgent) Reset() {
	*x = Spec_CustomAgent{}
	mi := &file_alis_ideate_spec_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_CustomAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_CustomAgent) ProtoMessage() {}

func (x *Spec_CustomAgent) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_CustomAgent.ProtoReflect.Descriptor instead.
func (*Spec_CustomAgent) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 17}
}

func (x *Spec_CustomAgent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A product requirements document.
type Spec_ProductRequirementsDocument struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The markdown content of the product requirements document.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_ProductRequirementsDocument) Reset() {
	*x = Spec_ProductRequirementsDocument{}
	mi := &file_alis_ideate_spec_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_ProductRequirementsDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_ProductRequirementsDocument) ProtoMessage() {}

func (x *Spec_ProductRequirementsDocument) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_ProductRequirementsDocument.ProtoReflect.Descriptor instead.
func (*Spec_ProductRequirementsDocument) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 18}
}

func (x *Spec_ProductRequirementsDocument) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// An agent feedback spec.
type Spec_AgentFeedback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent cards associated with the feedback.
	TargetAgents []*Spec_AgentFeedback_TargetAgent `protobuf:"bytes,1,rep,name=target_agents,json=targetAgents,proto3" json:"target_agents,omitempty"`
	// The markdown content of the agent feedback.
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_AgentFeedback) Reset() {
	*x = Spec_AgentFeedback{}
	mi := &file_alis_ideate_spec_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_AgentFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_AgentFeedback) ProtoMessage() {}

func (x *Spec_AgentFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_AgentFeedback.ProtoReflect.Descriptor instead.
func (*Spec_AgentFeedback) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 19}
}

func (x *Spec_AgentFeedback) GetTargetAgents() []*Spec_AgentFeedback_TargetAgent {
	if x != nil {
		return x.TargetAgents
	}
	return nil
}

func (x *Spec_AgentFeedback) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Spec_GenerationContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CEL filter to apply to the set of Streams that are used in the
	// Generation Leaving it empty will result in all Streams being used. Can
	// apply other filters to the set of Streams such as:
	//   - By ContributionSession: `Stream.contribution_session =
	//     "contributionSessions/1234567890"`
	//   - By set of Streams: `Stream.name in ("ideas/abc/streams/1234567890",
	//     "ideas/abc/streams/0987654321")`
	//   - By excluding set of Streams: `Stream.name not in
	//     ("ideas/abc/streams/1234567890", "ideas/abc/streams/0987654321")`
	//   - By contributor of streams: `Stream.contributor = "users/1234567890"`
	//   - By excluding contributor of streams: `Stream.contributor NOT
	//     "users/1234567890"`
	//   - By creation time: `Stream.create_time.seconds < 1742961600`
	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// User-defined instructions, provided to guide the generation process
	Instructions  string `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_GenerationContext) Reset() {
	*x = Spec_GenerationContext{}
	mi := &file_alis_ideate_spec_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_GenerationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_GenerationContext) ProtoMessage() {}

func (x *Spec_GenerationContext) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_GenerationContext.ProtoReflect.Descriptor instead.
func (*Spec_GenerationContext) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 20}
}

func (x *Spec_GenerationContext) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *Spec_GenerationContext) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

// Definition of TargetAgent
type Spec_AgentFeedback_TargetAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of Agent Stream
	// Format: ideas/*/streams/*
	AgentStream string `protobuf:"bytes,1,opt,name=agent_stream,json=agentStream,proto3" json:"agent_stream,omitempty"`
	// The agent card of the target agent
	AgentCard *AgentCard `protobuf:"bytes,2,opt,name=agent_card,json=agentCard,proto3" json:"agent_card,omitempty"`
	// A high-level overview of the Agent based on the Agent Card description
	Overview      string `protobuf:"bytes,3,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec_AgentFeedback_TargetAgent) Reset() {
	*x = Spec_AgentFeedback_TargetAgent{}
	mi := &file_alis_ideate_spec_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec_AgentFeedback_TargetAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_AgentFeedback_TargetAgent) ProtoMessage() {}

func (x *Spec_AgentFeedback_TargetAgent) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_spec_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_AgentFeedback_TargetAgent.ProtoReflect.Descriptor instead.
func (*Spec_AgentFeedback_TargetAgent) Descriptor() ([]byte, []int) {
	return file_alis_ideate_spec_proto_rawDescGZIP(), []int{0, 19, 0}
}

func (x *Spec_AgentFeedback_TargetAgent) GetAgentStream() string {
	if x != nil {
		return x.AgentStream
	}
	return ""
}

func (x *Spec_AgentFeedback_TargetAgent) GetAgentCard() *AgentCard {
	if x != nil {
		return x.AgentCard
	}
	return nil
}

func (x *Spec_AgentFeedback_TargetAgent) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

var File_alis_ideate_spec_proto protoreflect.FileDescriptor

const file_alis_ideate_spec_proto_rawDesc = "" +
	"\n" +
	"\x16alis/ideate/spec.proto\x12\valis.ideate\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1calis/ideate/agent_card.proto\"\x8f\x1e\n" +
	"\x04Spec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.alis.ideate.Spec.TypeR\x04type\x12\x12\n" +
	"\x04idea\x18\x04 \x01(\tR\x04idea\x12-\n" +
	"\x05state\x18\x05 \x01(\x0e2\x17.alis.ideate.Spec.StateR\x05state\x126\n" +
	"\bfull_rfp\x18\x06 \x01(\v2\x19.alis.ideate.Spec.FullRfpH\x00R\afullRfp\x12<\n" +
	"\n" +
	"idea_brief\x18\a \x01(\v2\x1b.alis.ideate.Spec.IdeaBriefH\x00R\tideaBrief\x129\n" +
	"\tui_design\x18\b \x01(\v2\x1a.alis.ideate.Spec.UiDesignH\x00R\buiDesign\x12B\n" +
	"\fai_prototype\x18\t \x01(\v2\x1d.alis.ideate.Spec.AiPrototypeH\x00R\vaiPrototype\x12?\n" +
	"\videate_spec\x18\n" +
	" \x01(\v2\x1c.alis.ideate.Spec.IdeateSpecH\x00R\n" +
	"ideateSpec\x12E\n" +
	"\rbusiness_case\x18\v \x01(\v2\x1e.alis.ideate.Spec.BusinessCaseH\x00R\fbusinessCase\x12K\n" +
	"\x0fcurrent_process\x18\f \x01(\v2 .alis.ideate.Spec.CurrentProcessH\x00R\x0ecurrentProcess\x122\n" +
	"\x06jargon\x18\r \x01(\v2\x18.alis.ideate.Spec.JargonH\x00R\x06jargon\x12Z\n" +
	"\x14technology_landscape\x18\x0e \x01(\v2%.alis.ideate.Spec.TechnologyLandscapeH\x00R\x13technologyLandscape\x12?\n" +
	"\vpain_points\x18\x0f \x01(\v2\x1c.alis.ideate.Spec.PainPointsH\x00R\n" +
	"painPoints\x12K\n" +
	"\x0fstakeholder_map\x18\x10 \x01(\v2 .alis.ideate.Spec.StakeholderMapH\x00R\x0estakeholderMap\x12<\n" +
	"\n" +
	"figma_make\x18\x11 \x01(\v2\x1b.alis.ideate.Spec.FigmaMakeH\x00R\tfigmaMake\x12x\n" +
	"\x1egemini_enterprise_custom_agent\x18\x12 \x01(\v21.alis.ideate.Spec.GeminiEnterpriseCustomAgentSpecH\x00R\x1bgeminiEnterpriseCustomAgent\x129\n" +
	"\tai_studio\x18\x13 \x01(\v2\x1a.alis.ideate.Spec.AiStudioH\x00R\baiStudio\x12R\n" +
	"\x12solution_flow_spec\x18\x14 \x01(\v2\".alis.ideate.Spec.SolutionFlowSpecH\x00R\x10solutionFlowSpec\x12E\n" +
	"\rresearch_plan\x18\x15 \x01(\v2\x1e.alis.ideate.Spec.ResearchPlanH\x00R\fresearchPlan\x12B\n" +
	"\fcustom_agent\x18\x16 \x01(\v2\x1d.alis.ideate.Spec.CustomAgentH\x00R\vcustomAgent\x12s\n" +
	"\x1dproduct_requirements_document\x18\x17 \x01(\v2-.alis.ideate.Spec.ProductRequirementsDocumentH\x00R\x1bproductRequirementsDocument\x12H\n" +
	"\x0eagent_feedback\x18\x18 \x01(\v2\x1f.alis.ideate.Spec.AgentFeedbackH\x00R\ragentFeedback\x12R\n" +
	"\x12generation_context\x18_ \x01(\v2#.alis.ideate.Spec.GenerationContextR\x11generationContext\x12\x1c\n" +
	"\toperation\x18` \x01(\tR\toperation\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12;\n" +
	"\vdelete_time\x18d \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deleteTime\x1a#\n" +
	"\aFullRfp\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a%\n" +
	"\tIdeaBrief\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a$\n" +
	"\bUiDesign\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a'\n" +
	"\vAiPrototype\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a&\n" +
	"\n" +
	"IdeateSpec\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a(\n" +
	"\fBusinessCase\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a,\n" +
	"\x10SolutionFlowSpec\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a'\n" +
	"\vCraftedSpec\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a*\n" +
	"\x0eCurrentProcess\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a\"\n" +
	"\x06Jargon\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a/\n" +
	"\x13TechnologyLandscape\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a&\n" +
	"\n" +
	"PainPoints\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a*\n" +
	"\x0eStakeholderMap\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a%\n" +
	"\tFigmaMake\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a\x8a\x01\n" +
	"\x1fGeminiEnterpriseCustomAgentSpec\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\finstructions\x18\x03 \x01(\tR\finstructions\x1a\x80\x01\n" +
	"\bAiStudio\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x121\n" +
	"\x14contribution_session\x18\x02 \x01(\tR\x13contributionSession\x12'\n" +
	"\x0fattachment_uris\x18\x03 \x03(\tR\x0eattachmentUris\x1a\x82\x01\n" +
	"\fResearchPlan\x12\x18\n" +
	"\aframing\x18\x01 \x01(\tR\aframing\x12-\n" +
	"\x12research_questions\x18\x02 \x03(\tR\x11researchQuestions\x12)\n" +
	"\x10leading_question\x18\x03 \x01(\tR\x0fleadingQuestion\x1a'\n" +
	"\vCustomAgent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a7\n" +
	"\x1bProductRequirementsDocument\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x1a\x81\x02\n" +
	"\rAgentFeedback\x12P\n" +
	"\rtarget_agents\x18\x01 \x03(\v2+.alis.ideate.Spec.AgentFeedback.TargetAgentR\ftargetAgents\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x1a\x83\x01\n" +
	"\vTargetAgent\x12!\n" +
	"\fagent_stream\x18\x01 \x01(\tR\vagentStream\x125\n" +
	"\n" +
	"agent_card\x18\x02 \x01(\v2\x16.alis.ideate.AgentCardR\tagentCard\x12\x1a\n" +
	"\boverview\x18\x03 \x01(\tR\boverview\x1aO\n" +
	"\x11GenerationContext\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\"\n" +
	"\finstructions\x18\x02 \x01(\tR\finstructions\"\xbb\x03\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bFULL_RFP\x10\x01\x12\x0e\n" +
	"\n" +
	"IDEA_BRIEF\x10\x05\x12\r\n" +
	"\tUI_DESIGN\x10\x06\x12\x10\n" +
	"\fAI_PROTOTYPE\x10\a\x12\x0f\n" +
	"\vIDEATE_SPEC\x10\b\x12\x11\n" +
	"\rBUSINESS_CASE\x10\t\x12\x16\n" +
	"\x12SOLUTION_FLOW_SPEC\x10\n" +
	"\x12\x10\n" +
	"\fCRAFTED_SPEC\x10\v\x12\x13\n" +
	"\x0fCURRENT_PROCESS\x10\f\x12\n" +
	"\n" +
	"\x06JARGON\x10\r\x12\x18\n" +
	"\x14TECHNOLOGY_LANDSCAPE\x10\x0e\x12\x0f\n" +
	"\vPAIN_POINTS\x10\x0f\x12\x13\n" +
	"\x0fSTAKEHOLDER_MAP\x10\x10\x12\x0e\n" +
	"\n" +
	"FIGMA_MAKE\x10\x11\x12\"\n" +
	"\x1eGEMINI_ENTERPRISE_CUSTOM_AGENT\x10\x12\x12\r\n" +
	"\tAI_STUDIO\x10\x13\x12\x11\n" +
	"\rRESEARCH_PLAN\x10\x14\x12\x10\n" +
	"\fCUSTOM_AGENT\x10\x15\x12!\n" +
	"\x1dPRODUCT_REQUIREMENTS_DOCUMENT\x10\x16\x12\x12\n" +
	"\x0eAGENT_FEEDBACK\x10\x17\"\x04\b\x02\x10\x02\"\x04\b\x03\x10\x03\"\x04\b\x04\x10\x04\"x\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DRAFT\x10\x01\x12\r\n" +
	"\tPUBLISHED\x10\x02\x12\f\n" +
	"\bARCHIVED\x10\x03\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x04\x12\t\n" +
	"\x05READY\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x06\x12\t\n" +
	"\x05STALE\x10\aB\b\n" +
	"\x06output\"]\n" +
	"\x0eGetSpecRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xaa\x01\n" +
	"\x1eGenerateCustomAgentSpecRequest\x12\x14\n" +
	"\x04idea\x18\x01 \x01(\tH\x00R\x04idea\x12\x14\n" +
	"\x04spec\x18\x02 \x01(\tH\x00R\x04spec\x12R\n" +
	"\x12generation_context\x18\x03 \x01(\v2#.alis.ideate.Spec.GenerationContextR\x11generationContextB\b\n" +
	"\x06source\"\x9a\x01\n" +
	"\x1fGenerateCustomAgentSpecMetadata\x12w\n" +
	"\"generate_custom_agent_spec_request\x18\x01 \x01(\v2+.alis.ideate.GenerateCustomAgentSpecRequestR\x1egenerateCustomAgentSpecRequest\"H\n" +
	"\x1fGenerateCustomAgentSpecResponse\x12%\n" +
	"\x04spec\x18\x01 \x01(\v2\x11.alis.ideate.SpecR\x04spec\"c\n" +
	"\x18RetrieveIdeaSpecsRequest\x12\x12\n" +
	"\x04idea\x18\x01 \x01(\tR\x04idea\x123\n" +
	"\tspec_type\x18\x02 \x01(\x0e2\x16.alis.ideate.Spec.TypeR\bspecType\"D\n" +
	"\x19RetrieveIdeaSpecsResponse\x12'\n" +
	"\x05specs\x18\x01 \x03(\v2\x11.alis.ideate.SpecR\x05specs\"\xd1\x01\n" +
	" GenerateAgentFeedbackSpecRequest\x12\x14\n" +
	"\x04idea\x18\x01 \x01(\tH\x00R\x04idea\x12\x14\n" +
	"\x04spec\x18\x02 \x01(\tH\x00R\x04spec\x12R\n" +
	"\x12generation_context\x18\x03 \x01(\v2#.alis.ideate.Spec.GenerationContextR\x11generationContext\x12#\n" +
	"\rtarget_agents\x18\x04 \x03(\tR\ftargetAgentsB\b\n" +
	"\x06source\"\xa2\x01\n" +
	"!GenerateAgentFeedbackSpecMetadata\x12}\n" +
	"$generate_agent_feedback_spec_request\x18\x01 \x01(\v2-.alis.ideate.GenerateAgentFeedbackSpecRequestR generateAgentFeedbackSpecRequest\"J\n" +
	"!GenerateAgentFeedbackSpecResponse\x12%\n" +
	"\x04spec\x18\x01 \x01(\v2\x11.alis.ideate.SpecR\x04specB0Z.github.com/alis-exchange/ideate-go/alis/ideateb\x06proto3"

var (
	file_alis_ideate_spec_proto_rawDescOnce sync.Once
	file_alis_ideate_spec_proto_rawDescData []byte
)

func file_alis_ideate_spec_proto_rawDescGZIP() []byte {
	file_alis_ideate_spec_proto_rawDescOnce.Do(func() {
		file_alis_ideate_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_ideate_spec_proto_rawDesc), len(file_alis_ideate_spec_proto_rawDesc)))
	})
	return file_alis_ideate_spec_proto_rawDescData
}

var file_alis_ideate_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_alis_ideate_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_alis_ideate_spec_proto_goTypes = []any{
	(Spec_Type)(0),                               // 0: alis.ideate.Spec.Type
	(Spec_State)(0),                              // 1: alis.ideate.Spec.State
	(*Spec)(nil),                                 // 2: alis.ideate.Spec
	(*GetSpecRequest)(nil),                       // 3: alis.ideate.GetSpecRequest
	(*GenerateCustomAgentSpecRequest)(nil),       // 4: alis.ideate.GenerateCustomAgentSpecRequest
	(*GenerateCustomAgentSpecMetadata)(nil),      // 5: alis.ideate.GenerateCustomAgentSpecMetadata
	(*GenerateCustomAgentSpecResponse)(nil),      // 6: alis.ideate.GenerateCustomAgentSpecResponse
	(*RetrieveIdeaSpecsRequest)(nil),             // 7: alis.ideate.RetrieveIdeaSpecsRequest
	(*RetrieveIdeaSpecsResponse)(nil),            // 8: alis.ideate.RetrieveIdeaSpecsResponse
	(*GenerateAgentFeedbackSpecRequest)(nil),     // 9: alis.ideate.GenerateAgentFeedbackSpecRequest
	(*GenerateAgentFeedbackSpecMetadata)(nil),    // 10: alis.ideate.GenerateAgentFeedbackSpecMetadata
	(*GenerateAgentFeedbackSpecResponse)(nil),    // 11: alis.ideate.GenerateAgentFeedbackSpecResponse
	(*Spec_FullRfp)(nil),                         // 12: alis.ideate.Spec.FullRfp
	(*Spec_IdeaBrief)(nil),                       // 13: alis.ideate.Spec.IdeaBrief
	(*Spec_UiDesign)(nil),                        // 14: alis.ideate.Spec.UiDesign
	(*Spec_AiPrototype)(nil),                     // 15: alis.ideate.Spec.AiPrototype
	(*Spec_IdeateSpec)(nil),                      // 16: alis.ideate.Spec.IdeateSpec
	(*Spec_BusinessCase)(nil),                    // 17: alis.ideate.Spec.BusinessCase
	(*Spec_SolutionFlowSpec)(nil),                // 18: alis.ideate.Spec.SolutionFlowSpec
	(*Spec_CraftedSpec)(nil),                     // 19: alis.ideate.Spec.CraftedSpec
	(*Spec_CurrentProcess)(nil),                  // 20: alis.ideate.Spec.CurrentProcess
	(*Spec_Jargon)(nil),                          // 21: alis.ideate.Spec.Jargon
	(*Spec_TechnologyLandscape)(nil),             // 22: alis.ideate.Spec.TechnologyLandscape
	(*Spec_PainPoints)(nil),                      // 23: alis.ideate.Spec.PainPoints
	(*Spec_StakeholderMap)(nil),                  // 24: alis.ideate.Spec.StakeholderMap
	(*Spec_FigmaMake)(nil),                       // 25: alis.ideate.Spec.FigmaMake
	(*Spec_GeminiEnterpriseCustomAgentSpec)(nil), // 26: alis.ideate.Spec.GeminiEnterpriseCustomAgentSpec
	(*Spec_AiStudio)(nil),                        // 27: alis.ideate.Spec.AiStudio
	(*Spec_ResearchPlan)(nil),                    // 28: alis.ideate.Spec.ResearchPlan
	(*Spec_CustomAgent)(nil),                     // 29: alis.ideate.Spec.CustomAgent
	(*Spec_ProductRequirementsDocument)(nil),     // 30: alis.ideate.Spec.ProductRequirementsDocument
	(*Spec_AgentFeedback)(nil),                   // 31: alis.ideate.Spec.AgentFeedback
	(*Spec_GenerationContext)(nil),               // 32: alis.ideate.Spec.GenerationContext
	(*Spec_AgentFeedback_TargetAgent)(nil),       // 33: alis.ideate.Spec.AgentFeedback.TargetAgent
	(*timestamppb.Timestamp)(nil),                // 34: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),                // 35: google.protobuf.FieldMask
	(*AgentCard)(nil),                            // 36: alis.ideate.AgentCard
}
var file_alis_ideate_spec_proto_depIdxs = []int32{
	0,  // 0: alis.ideate.Spec.type:type_name -> alis.ideate.Spec.Type
	1,  // 1: alis.ideate.Spec.state:type_name -> alis.ideate.Spec.State
	12, // 2: alis.ideate.Spec.full_rfp:type_name -> alis.ideate.Spec.FullRfp
	13, // 3: alis.ideate.Spec.idea_brief:type_name -> alis.ideate.Spec.IdeaBrief
	14, // 4: alis.ideate.Spec.ui_design:type_name -> alis.ideate.Spec.UiDesign
	15, // 5: alis.ideate.Spec.ai_prototype:type_name -> alis.ideate.Spec.AiPrototype
	16, // 6: alis.ideate.Spec.ideate_spec:type_name -> alis.ideate.Spec.IdeateSpec
	17, // 7: alis.ideate.Spec.business_case:type_name -> alis.ideate.Spec.BusinessCase
	20, // 8: alis.ideate.Spec.current_process:type_name -> alis.ideate.Spec.CurrentProcess
	21, // 9: alis.ideate.Spec.jargon:type_name -> alis.ideate.Spec.Jargon
	22, // 10: alis.ideate.Spec.technology_landscape:type_name -> alis.ideate.Spec.TechnologyLandscape
	23, // 11: alis.ideate.Spec.pain_points:type_name -> alis.ideate.Spec.PainPoints
	24, // 12: alis.ideate.Spec.stakeholder_map:type_name -> alis.ideate.Spec.StakeholderMap
	25, // 13: alis.ideate.Spec.figma_make:type_name -> alis.ideate.Spec.FigmaMake
	26, // 14: alis.ideate.Spec.gemini_enterprise_custom_agent:type_name -> alis.ideate.Spec.GeminiEnterpriseCustomAgentSpec
	27, // 15: alis.ideate.Spec.ai_studio:type_name -> alis.ideate.Spec.AiStudio
	18, // 16: alis.ideate.Spec.solution_flow_spec:type_name -> alis.ideate.Spec.SolutionFlowSpec
	28, // 17: alis.ideate.Spec.research_plan:type_name -> alis.ideate.Spec.ResearchPlan
	29, // 18: alis.ideate.Spec.custom_agent:type_name -> alis.ideate.Spec.CustomAgent
	30, // 19: alis.ideate.Spec.product_requirements_document:type_name -> alis.ideate.Spec.ProductRequirementsDocument
	31, // 20: alis.ideate.Spec.agent_feedback:type_name -> alis.ideate.Spec.AgentFeedback
	32, // 21: alis.ideate.Spec.generation_context:type_name -> alis.ideate.Spec.GenerationContext
	34, // 22: alis.ideate.Spec.create_time:type_name -> google.protobuf.Timestamp
	34, // 23: alis.ideate.Spec.update_time:type_name -> google.protobuf.Timestamp
	34, // 24: alis.ideate.Spec.delete_time:type_name -> google.protobuf.Timestamp
	35, // 25: alis.ideate.GetSpecRequest.read_mask:type_name -> google.protobuf.FieldMask
	32, // 26: alis.ideate.GenerateCustomAgentSpecRequest.generation_context:type_name -> alis.ideate.Spec.GenerationContext
	4,  // 27: alis.ideate.GenerateCustomAgentSpecMetadata.generate_custom_agent_spec_request:type_name -> alis.ideate.GenerateCustomAgentSpecRequest
	2,  // 28: alis.ideate.GenerateCustomAgentSpecResponse.spec:type_name -> alis.ideate.Spec
	0,  // 29: alis.ideate.RetrieveIdeaSpecsRequest.spec_type:type_name -> alis.ideate.Spec.Type
	2,  // 30: alis.ideate.RetrieveIdeaSpecsResponse.specs:type_name -> alis.ideate.Spec
	32, // 31: alis.ideate.GenerateAgentFeedbackSpecRequest.generation_context:type_name -> alis.ideate.Spec.GenerationContext
	9,  // 32: alis.ideate.GenerateAgentFeedbackSpecMetadata.generate_agent_feedback_spec_request:type_name -> alis.ideate.GenerateAgentFeedbackSpecRequest
	2,  // 33: alis.ideate.GenerateAgentFeedbackSpecResponse.spec:type_name -> alis.ideate.Spec
	33, // 34: alis.ideate.Spec.AgentFeedback.target_agents:type_name -> alis.ideate.Spec.AgentFeedback.TargetAgent
	36, // 35: alis.ideate.Spec.AgentFeedback.TargetAgent.agent_card:type_name -> alis.ideate.AgentCard
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_alis_ideate_spec_proto_init() }
func file_alis_ideate_spec_proto_init() {
	if File_alis_ideate_spec_proto != nil {
		return
	}
	file_alis_ideate_agent_card_proto_init()
	file_alis_ideate_spec_proto_msgTypes[0].OneofWrappers = []any{
		(*Spec_FullRfp_)(nil),
		(*Spec_IdeaBrief_)(nil),
		(*Spec_UiDesign_)(nil),
		(*Spec_AiPrototype_)(nil),
		(*Spec_IdeateSpec_)(nil),
		(*Spec_BusinessCase_)(nil),
		(*Spec_CurrentProcess_)(nil),
		(*Spec_Jargon_)(nil),
		(*Spec_TechnologyLandscape_)(nil),
		(*Spec_PainPoints_)(nil),
		(*Spec_StakeholderMap_)(nil),
		(*Spec_FigmaMake_)(nil),
		(*Spec_GeminiEnterpriseCustomAgent)(nil),
		(*Spec_AiStudio_)(nil),
		(*Spec_SolutionFlowSpec_)(nil),
		(*Spec_ResearchPlan_)(nil),
		(*Spec_CustomAgent_)(nil),
		(*Spec_ProductRequirementsDocument_)(nil),
		(*Spec_AgentFeedback_)(nil),
	}
	file_alis_ideate_spec_proto_msgTypes[2].OneofWrappers = []any{
		(*GenerateCustomAgentSpecRequest_Idea)(nil),
		(*GenerateCustomAgentSpecRequest_Spec)(nil),
	}
	file_alis_ideate_spec_proto_msgTypes[7].OneofWrappers = []any{
		(*GenerateAgentFeedbackSpecRequest_Idea)(nil),
		(*GenerateAgentFeedbackSpecRequest_Spec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_ideate_spec_proto_rawDesc), len(file_alis_ideate_spec_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_ideate_spec_proto_goTypes,
		DependencyIndexes: file_alis_ideate_spec_proto_depIdxs,
		EnumInfos:         file_alis_ideate_spec_proto_enumTypes,
		MessageInfos:      file_alis_ideate_spec_proto_msgTypes,
	}.Build()
	File_alis_ideate_spec_proto = out.File
	file_alis_ideate_spec_proto_goTypes = nil
	file_alis_ideate_spec_proto_depIdxs = nil
}
