// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: alis/ideate/stream.proto

package ideate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The potential states of a Stream
type Stream_State int32

const (
	// Unspecified state
	Stream_STATE_UNSPECIFIED Stream_State = 0
	// In certain cases (eg. File Upload), a Stream is created before any
	// content actually exists and requires the client side to upload before
	Stream_UPLOAD_PENDING Stream_State = 1
	// The Stream is considered NEW when initially added
	// and still needs to be parsed
	Stream_NEW Stream_State = 2
	// The stream file data is actively being preprocessed
	Stream_PREPROCESSING Stream_State = 3
	// The stream is actively being augmented by the model
	Stream_AUGMENTING Stream_State = 4
	// The GenAI processing has completed successfully and the Stream has
	// been enriched. This is a key success state.
	Stream_READY Stream_State = 5
	// Failed to parse the content of the Stream
	Stream_FAILED Stream_State = 6
	// The Stream is no longer active. This could be a terminal state for
	// Streams that are discarded or have been fully actioned and are kept
	// for historical purposes.
	Stream_ARCHIVED Stream_State = 7
)

// Enum value maps for Stream_State.
var (
	Stream_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "UPLOAD_PENDING",
		2: "NEW",
		3: "PREPROCESSING",
		4: "AUGMENTING",
		5: "READY",
		6: "FAILED",
		7: "ARCHIVED",
	}
	Stream_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"UPLOAD_PENDING":    1,
		"NEW":               2,
		"PREPROCESSING":     3,
		"AUGMENTING":        4,
		"READY":             5,
		"FAILED":            6,
		"ARCHIVED":          7,
	}
)

func (x Stream_State) Enum() *Stream_State {
	p := new(Stream_State)
	*p = x
	return p
}

func (x Stream_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stream_State) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_ideate_stream_proto_enumTypes[0].Descriptor()
}

func (Stream_State) Type() protoreflect.EnumType {
	return &file_alis_ideate_stream_proto_enumTypes[0]
}

func (x Stream_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stream_State.Descriptor instead.
func (Stream_State) EnumDescriptor() ([]byte, []int) {
	return file_alis_ideate_stream_proto_rawDescGZIP(), []int{0, 0}
}

// A Stream represents a continuous flow of information and insights,
// capturing how ideas move, merge, and transform; and showcasing the
// Idea through its developmental journey.
//
// Metaphorically, a Stream can be seen as flowing water of information,
// with each Stream contribution representing a tributary that joins the main
// Idea river, adding momentum, shaping and redirecting the Idea's course.
//
// Key Characteristics:
//   - Organic Growth: Streams capture the metaphorical journey
//     of an Idea, showing how it grows and transforms over time;
//   - Fluid Composition: Supports multiple content types
//     including text notes, voice recordings, screen captures,
//     links, images, and audio;
//   - Dynamic Progression: Captures the non-linear movement of an Idea;
//   - Chronological Mapping: Maintains a clear timeline of contributions,
//     tracking the Idea's flow.
//
// Example Scenario:
//   - A voice note as the first Stream origin of an Idea;
//
// As time progresses, the user then goes and adds new Streams:
//   - Screen recordings showing how the current process works;
//   - Notes around the business requirements;
//   - Opens a discussion around what elements are important;
//   - Uploads a data file for context; and
//   - Links to online resources.
type Stream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique name of the Stream which cannot be changed.
	// Format: ideas/([a-zA-Z0-9_-]{1,128})/streams/([a-z0-9-]{2,50}$)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The display name of the Stream.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Associated Contribution Session if the Stream was added as part
	// of a Contribution Session.
	//
	// Format: contributionSessions/*
	ContributionSession string `protobuf:"bytes,3,opt,name=contribution_session,json=contributionSession,proto3" json:"contribution_session,omitempty"`
	// The state of the Stream
	State Stream_State `protobuf:"varint,4,opt,name=state,proto3,enum=alis.ideate.Stream_State" json:"state,omitempty"`
	// The creation time of the Stream
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,97,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last time the Stream was updated
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_alis_ideate_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_alis_ideate_stream_proto_rawDescGZIP(), []int{0}
}

func (x *Stream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stream) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Stream) GetContributionSession() string {
	if x != nil {
		return x.ContributionSession
	}
	return ""
}

func (x *Stream) GetState() Stream_State {
	if x != nil {
		return x.State
	}
	return Stream_STATE_UNSPECIFIED
}

func (x *Stream) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Stream) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Request message for GetStream
type GetStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the Stream to get
	// Format: ideas/*/streams/*
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The fields to return in snake_case.
	// All fields are returned if not set.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRequest) Reset() {
	*x = GetStreamRequest{}
	mi := &file_alis_ideate_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRequest) ProtoMessage() {}

func (x *GetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ideate_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRequest.ProtoReflect.Descriptor instead.
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return file_alis_ideate_stream_proto_rawDescGZIP(), []int{1}
}

func (x *GetStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStreamRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

var File_alis_ideate_stream_proto protoreflect.FileDescriptor

const file_alis_ideate_stream_proto_rawDesc = "" +
	"\n" +
	"\x18alis/ideate/stream.proto\x12\valis.ideate\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x03\n" +
	"\x06Stream\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x121\n" +
	"\x14contribution_session\x18\x03 \x01(\tR\x13contributionSession\x12/\n" +
	"\x05state\x18\x04 \x01(\x0e2\x19.alis.ideate.Stream.StateR\x05state\x12;\n" +
	"\vcreate_time\x18a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\x83\x01\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUPLOAD_PENDING\x10\x01\x12\a\n" +
	"\x03NEW\x10\x02\x12\x11\n" +
	"\rPREPROCESSING\x10\x03\x12\x0e\n" +
	"\n" +
	"AUGMENTING\x10\x04\x12\t\n" +
	"\x05READY\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x06\x12\f\n" +
	"\bARCHIVED\x10\a\"_\n" +
	"\x10GetStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMaskB0Z.github.com/alis-exchange/ideate-go/alis/ideateb\x06proto3"

var (
	file_alis_ideate_stream_proto_rawDescOnce sync.Once
	file_alis_ideate_stream_proto_rawDescData []byte
)

func file_alis_ideate_stream_proto_rawDescGZIP() []byte {
	file_alis_ideate_stream_proto_rawDescOnce.Do(func() {
		file_alis_ideate_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_ideate_stream_proto_rawDesc), len(file_alis_ideate_stream_proto_rawDesc)))
	})
	return file_alis_ideate_stream_proto_rawDescData
}

var file_alis_ideate_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alis_ideate_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alis_ideate_stream_proto_goTypes = []any{
	(Stream_State)(0),             // 0: alis.ideate.Stream.State
	(*Stream)(nil),                // 1: alis.ideate.Stream
	(*GetStreamRequest)(nil),      // 2: alis.ideate.GetStreamRequest
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 4: google.protobuf.FieldMask
}
var file_alis_ideate_stream_proto_depIdxs = []int32{
	0, // 0: alis.ideate.Stream.state:type_name -> alis.ideate.Stream.State
	3, // 1: alis.ideate.Stream.create_time:type_name -> google.protobuf.Timestamp
	3, // 2: alis.ideate.Stream.update_time:type_name -> google.protobuf.Timestamp
	4, // 3: alis.ideate.GetStreamRequest.read_mask:type_name -> google.protobuf.FieldMask
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_alis_ideate_stream_proto_init() }
func file_alis_ideate_stream_proto_init() {
	if File_alis_ideate_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_ideate_stream_proto_rawDesc), len(file_alis_ideate_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_ideate_stream_proto_goTypes,
		DependencyIndexes: file_alis_ideate_stream_proto_depIdxs,
		EnumInfos:         file_alis_ideate_stream_proto_enumTypes,
		MessageInfos:      file_alis_ideate_stream_proto_msgTypes,
	}.Build()
	File_alis_ideate_stream_proto = out.File
	file_alis_ideate_stream_proto_goTypes = nil
	file_alis_ideate_stream_proto_depIdxs = nil
}
