// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/ideate/stream.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-06-09 18:17:16 UTC

package ideate

const ()
