// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/ideate/stream.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-03-05 06:12:17 UTC

package ideate

const ()
